### ISSUE TITLE
Filamant Sesor

### ISSUE THREAD

**Issue by soner4** [TheZeroBeast/MM-control-01#100]
Hi All,
  
I am planning to flash the TheZeroBeast firmware for my MMU2. I saw the messages on Prusa Firmware git. Some people mention that two weeks ago when they flashed the firmware the filament sensor on the printer becoming N/A. Is this still an issue or  it is updated? 

https://github.com/prusa3d/Prusa-Firmware/issues/1163

**Comment by TheZeroBeast** [comment]
Might well be but no cause identified for that one case.
