### ISSUE TITLE
Stuck homing selector on 2.1.8

### ISSUE THREAD

**Issue by Phydam** [TheZeroBeast/MM-control-01#101]
After updating to 2.1.8, I have a strange issue. On initiating a print on the first load it homes the selector continuously until i reset the printer. I've also tried just moving the selector after rebooting the printer and it does the same thing. I rolled back to 2.1.6 and the issue goes away.

**Comment by TheZeroBeast** [comment]
@Phydam try reflashing mmu code and if still no luck double check hardware.
I.e. no blade, no tight spots on selector travel.

**Comment by TheZeroBeast** [comment]
closing due to lack of response.

**Comment by Phydam** [comment]
updated to RC2 and it's fine. not sure what caused it on RC1.
