### ISSUE TITLE
MMU-MK3 2.1.8-RC2 - Flashing failed

### ISSUE THREAD

**Issue by wieckowy** [TheZeroBeast/MM-control-01#104]
Hey.
I have a problem with flashing the latest MMU firmware.

I'm getting an error:

> avrdude: stk500v2_recv(): timeout
> avrdude: stk500v2_getsync(): timeout communicating with programmer

![2019-01-27_085533](https://user-images.githubusercontent.com/1842207/51798383-56596b80-2211-11e9-90b2-2f226a13de1e.jpg)

Previous versions are flashing without a problem.

Thank you for your help!
Best regards
Lukasz Wiecek

**Comment by TheZeroBeast** [comment]
Nice, thanks, fixing now 🤦‍♂️ forgot to add a bit to hex

**Comment by TheZeroBeast** [comment]
@wieckowy should do it's job now mate 👍
