### ISSUE TITLE
Calibrating filament channels separately

### ISSUE THREAD

**Issue by MarioWolter** [TheZeroBeast/MM-control-01#105]
Hi,

I really love your MMU2 firmware! I am able to print quite nicely, however, I have some grinding in the MMU2 pulleys.

I have calibrated bowden length and Sensor to bondtech length according to the readme.
However, if I calibrate the first channel flush to the end of the bowden tube, my fourth channel filament will never reach the filament sensor above the extruder.

This seems to be connected to the issue reported in the release notes of theofficial MMU firmware: "MMU2 pulleys diameter can vary because of manufacturing tolerances."

Therefore I needed an option to calibrate my channels independently!

My current workaround is to calibrate the bowden length longer than necessary on the first channel, just enough to get the fourth channel going. However, as mentioned abve, this seems to lead to some grinding on the other channels.

Thanks a lot for the amazing work up until now!

Mario

**Comment by TheZeroBeast** [comment]
Hi @MarioWolter,

Glad you've been able to get it mostly working and I will not be adding independent channel calibration sorry. The approach to solve is as you already have done by calibrating just past flush with your tube until the ~35mm sensing ballpark covers all five channels.

Flush covers those with passthrough connectors that end just before FSensor.
