### ISSUE TITLE
new firmware, now printer and MMU don't communicate

### ISSUE THREAD

**Issue by YoungR0se** [TheZeroBeast/MM-control-01#106]
I have just upgraded to the latest firmware release, MMU: V#: 2.1.8 RC2 B#: 304 and
MK3: B#: 2386 on both the printer and MMU2.  With only one modification to the printer firmware, I flashed both, printer first, then MMU.  Now the two systems are not communicating properly.  The printer show MMU capabilities in the menu, like load to nozzle etc, but nono of the commands from the printer affect the MMU.  Printing a gcode results in the printer going through the motions of mesh bed leveling and then beginning the print without ever loading the filament.  The MMU will pre-load the filament to the FINDA, but will not respond to printer commands to load to nozzle or eject.  Wtf?  I have tried flashing from Arduino (different versions for different boards) and also compiling HEX files and flashing from Slic3r.  Made no difference.  Any suggestions?

**Comment by TheZeroBeast** [comment]
Must be a bug, please provide log files and gcode for me to progress this investigation when possible.

**Comment by YoungR0se** [comment]
Hi,
Thanks for taking the time to look into this :) I don't know how to provide gcode, so attached are the firmware files that I used.  The MMU is unaltered, the printer has Z axis increased to 350mm.  
In addition to yesterdays info, I reflashed the firmware today while I was preparing this for you.  When I preheated the printer on the screen between 'SD%' and 'time remaining', it says 'F83'.  When temp was attained, I tried to load Filament 1, which was successful.  Then I tried to load Filament 2, which was not.  I selected Filament 2 from the loading menu and nothing happened.  Upon returning to the home screen, the 'F83' has now become '83[right arrow]1, and the status bar says 'MMU Loading Ext: 1'.  

[30-01-19 Logfile MK3 B 2386.docx](https://github.com/TheZeroBeast/MM-control-01/files/2810018/30-01-19.Logfile.MK3.B.2386.docx)
[30-01-19 Log file MMU V 2.1.8 RC2 B 304.docx](https://github.com/TheZeroBeast/MM-control-01/files/2810019/30-01-19.Log.file.MMU.V.2.1.8.RC2.B.304.docx)

[Attempted flash of MMU V 2.1.8 RC2 B 304 firmware.zip](https://github.com/TheZeroBeast/MM-control-01/files/2810022/Attempted.flash.of.MMU.V.2.1.8.RC2.B.304.firmware.zip)
[Attempted flash of MK3 B 2386 firmware.zip](https://github.com/TheZeroBeast/MM-control-01/files/2810023/Attempted.flash.of.MK3.B.2386.firmware.zip)

**Comment by YoungR0se** [comment]
Yo, it's been two weeks.  Anything changed?  Bug fixed?  I've kept an eye on the page but no new files have been added, the most recent was 16 days ago.

P.S. I just found your page about The Frog, I will definitely look into putting it on my printer.  Apologies for sounding impatient above, but someone is ridding me to get the printer working reliably.

**Comment by TheZeroBeast** [comment]
Hi @youngr0se,

I had a quick look at your provided files last night and couldn’t find any smoking gun.

There’s no obvious reason why communications wouldn’t be working, please check your hardware.

**Comment by YoungR0se** [comment]
Ok, thanks for the info

**Comment by AbeFM** [comment]
Not sure if you've figured it out, but have you checked that your sensor is seeing your filament reliably? Certainly that was an issue that had caused similar behavior in the past for me.

**Comment by TheZeroBeast** [comment]
Stale. Closing
