### ISSUE TITLE
Filament

### ISSUE THREAD

**Issue by gizzburn** [TheZeroBeast/MM-control-01#109]
Hi Robert not sure if this is an issue or not, but I cant get my prints to do the purge lines at the start of the prints, its like the filament is not going far enough in the extruder.
I have done both of the calibrations for the tube and gear setup but its still the same.

I even went back to a earlier version of TZB with the same results. It starts to print but some of the start is missing. no clogs or jams as it extrudes when I manually try it.

By the way the other issue I had was my central heating boiler, had a new one fitted with a new wifi controller, it was this controller that was interfering with the wifi on my pi3 with Octoprint...

Ok update after some testing its only my position 5 that is the problem, all the others work just fine. When I use position 5 the extruder starts to move to soon, it moves before the filament has got to the bondtech gears, all the other positions move much later, will do some more testing.

Well Robert its not a bug, it turns out its my Profile must have got corrupted, I went back to the standard presets and it worked fine, so you can close this post..

thanks for your hard work..

**Comment by TheZeroBeast** [comment]
Yep, you found it but Slic3r loves to stuff up and do default on a channel sometimes which stuffs the load/unload on that channel for the gcode.
