### ISSUE TITLE
Question about motor currents

### ISSUE THREAD

**Issue by sergiofagundes** [TheZeroBeast/MM-control-01#112]
What the numbers settings in currents for pulley, selector and idler means ?
In the following codes for example:

// currents for pulley, selector and idler
#define CURRENT_HOLDING_STEALTH        { 1,  7, 16}
#define CURRENT_HOLDING_NORMAL         { 1, 10, 10}
#define CURRENT_HOLDING_NORMAL_LOADING { 1, 10, 40}
#define CURRENT_RUNNING_STEALTH        {30, 35, 35}
#define CURRENT_RUNNING_NORMAL         {30, 35, 40}
#define CURRENT_HOMING                 { 1, 35, 35}

**Comment by TheZeroBeast** [comment]
the current amount used to drive the motors at different times.

**Comment by sergiofagundes** [comment]
> the current amount used to drive the motors at different times.

Hi, how to set for example a pulley stepper for a 500mA ? How these numbers are related to the mA ?

I have made a research in the tmc2130.c file and noted the bellow:
* @param current_h: hold current 0...63 (15mA...960mA RMS, @ R_sens = 0.22 Ohm)

So currents have a window of 15-960mA, and each number (from 64 in total) represents 15mA, if I use 33 I get 495mA, is this right ?


Thank you

**Comment by TheZeroBeast** [comment]
Stale. Closing
