### ISSUE TITLE
Suggestion: Blob Detection

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#114]
When rewinding filament during a change,. I find (with JLTX's cool selector part) I can see the blobs go by. In fact, you can see the ball drop for the string, then rise again as the blob passes.

Perhaps with a blade, a cut could be made, or a count could be made of blobs seen.

I'm not 100% sure what it's useful for, but I bet it's something you could keep track of.

**Comment by TheZeroBeast** [comment]
Stale. Closing. Not on my wish list at present, we'll see if still required in 6months.
