### ISSUE TITLE
Load Failure Timeout Pause Print

### ISSUE THREAD

**Issue by TheZeroBeast** [TheZeroBeast/MM-control-01#13]
When a load fails printer remains ready for the MK3-FSensor to trip and pull filament in.

Implement a timeout to pause if in state longer than 5m.
Autorecover hotend heater, complete failed load once fixed and continue.

**Comment by jettoblack** [comment]
That sounds pretty important. :)

**Comment by TheZeroBeast** [comment]
Yes, good idea if I can. Not a code god by any measure.

**Comment by jettoblack** [comment]
The Prusa FW already had this, if the MMU doesn't respond for a while, it will move the carriage to the back corner and shut off the hotend heater. Does it not work on yours because the MK3 is waiting for the filament sensor to trigger instead of waiting for a MMU response?

**Comment by TheZeroBeast** [comment]
It does but when you’re not taking between each other, should be able to change it to work in another situation 👍🤔

**Comment by TheZeroBeast** [comment]
https://github.com/TheZeroBeast/Prusa-Firmware/pull/15 solves this issue, more testing before merging.

**Comment by TheZeroBeast** [comment]
This feature is now incorporated into the latest release MMU-2.1.3 & MK3 5.1.2.

5m timeout.

Clear MMU fault then clear MK3 fault, from testing this has recovered great so far 👍

**Comment by AbeFM** [comment]
How do people feel about the 5 minutes? To me it was always too long.

**Comment by TheZeroBeast** [comment]
This can be changed easy enough, it’s a MK3 default. Maybe 1m without communications.

**Comment by jettoblack** [comment]
1 min is too short to notice and fix a problem. I'm ok with 5 mins since that's Prusa's default.

**Comment by AbeFM** [comment]
My feeling is 3, but it is no hill to die on.

**Comment by AbeFM** [comment]
Separate from that time length.. As I've now had a few failures with the firmware, often I find the MMU ready to go but nothing happens. I *think* it;s after I press the MK3's button, wait for it to reheat, and then it'll go? If so, I'd be happy to try to reword it from "press button on MMU" which I do a lot of times and nothing happens. :-)
