### ISSUE TITLE
MMU 3.0.0RC2 Hex doesn't upload

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#132]
Prusa's slicer doesn't see the MMU2 code as MMU2, I believe. Ordinarily, it displays "auto" for com port but when I load this hex it does not.

**Comment by AbeFM** [comment]
Aside from the report, any advice on loading RC2 onto the MMU would be appreciated, perhaps I'm missing something?

**Comment by AbeFM** [comment]
I'm missing "; device = mm-control" as mentioned in the readme. It'd still be nice if it were in the release.

**Comment by TheZeroBeast** [comment]
Yes, normally is 🤦‍♂️ don't release at midnight 😅 fixing now
