### ISSUE TITLE
3.0.0RC1 - loses coms on reset

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#133]
During a print, something went wrong and I reset the MMU. It's possible that the filament was down the tube but neither bunched against nor taken into the extruder - but I am uncertain.

I pulled back filament, reset MMU, and nothing happened. After I ran the pre-load a couple times, and left and right just moved selector, I resumed print, and head went to purge block and just sat.

Pause print, manually load, resume print, it unloads, goes to next filament, loads and resumes.

On the next load, it was just sitting there (fully hot)on the purge block. Same pause-manual load-unpause. 

This happened for the next few loads when I upgraded to RC2. Am waiting on MMU code I can figure out how to install. Will get better notes if it happens on RC2, but it seems like there is some information not being sent to the MMU that should tell it what state it needs to be in to finish a print. I think going to the far right made the screen on the printer blank, but again, I can't swear it.

**Comment by TheZeroBeast** [comment]
Once your MMU2S is reset it will lose comms for sure.

So, RC1 code on this. Try RC2 and report back please.

**Comment by AbeFM** [comment]
I have been unable to get RC2 to load filament. I could try with PLA, it might work.

**Comment by TheZeroBeast** [comment]
No longer an issue.

**Comment by AbeFM** [comment]
As in... Fixed in Version XXXXX?

**Comment by TheZeroBeast** [comment]
Your loading issue which is fixed in 3.0.0-RC2.

No comms on a MMU2S reset is what happens.
If you get into a state which appears like you’re itching to reset the MMU2S (when on latest release code or newer) please provide details on what you were attempting, the of events that led you to the issue and the serial log of it so I can attempt to resolve.

**Comment by AbeFM** [comment]
So it's a "will not fix". Trying to understand. These issues go away sometimes before I'm convinced they are dealt with.

Generally the issue is that nothing is moving and there is something mechanically jammed - filament wrapped around the gear either in the extruder or in the mmu, and physically moving the parts is hard when they are held.

Admittedly, I use reset because it works - it means "you can't trust the state you're in, please figure out where you should be and go there". In my simplified view, on reset, the MMU asks the printer what's going on, and the printer says "you should be loading filament 3" and everything picks up.

Assuming I don't have serial logs, what information would you like to help with these issues?

**Comment by TheZeroBeast** [comment]
I don’t see this as an issue needing fixing, not that it’s impossible.

Almost all error states have drivers disengaged for troubleshooting.

If you would like to workout state handling comms in a fork I surely can add it in 👌🤗
