### ISSUE TITLE
bondtech and bear

### ISSUE THREAD

**Issue by fredmz01** [TheZeroBeast/MM-control-01#139]
hello, simple precision, the firmware is it compatible with an extruder Bondtech MK3S and a frame Bear? thank you very much

**Comment by TheZeroBeast** [comment]
Hey mate, it’s never been tested on such. What changes does the bondtech introduce to the stock PRUSA firmware?

**Comment by fredmz01** [comment]
just change the e-step, so normally it should work

**Comment by TheZeroBeast** [comment]
Should be no problem.
You may have issues if you hit the max step per second rate which I think happens if you run 3:1 gears and 0.8deg stepper on the default stepper resolution.

**Comment by TheZeroBeast** [comment]
@fredmz01, re-open if you have questions getting it working, happy to help.
