### ISSUE TITLE
Linear advance 1.5 feature

### ISSUE THREAD

**Issue by FredMk3** [TheZeroBeast/MM-control-01#149]
Hi and thanks for your work.
Did you plan to make a version with LA 1.5 include?
I test the vertigo firmware LA 1.5 and extruder bunnyscience with e3dv6 stock and the result is very good. A mix of your work for great set my mmu2 and LA 1.5 is for me and sure other a good solution 😉

**Comment by TheZeroBeast** [comment]
Hi @FredMk3, glad to hear it makes a difference. I hear PRUSA plan to implement LA2 in the stock FW in the near future so I will re-base my FW to the new stock versions when they're released.
