### ISSUE TITLE
Support for Bondtech Mosquito

### ISSUE THREAD

**Issue by rmilyard** [TheZeroBeast/MM-control-01#150]
I have a MK3S+MMU2S with Bondtech Mosquito extruder.  I have been having a lot of issues getting this all working together.  I was wondering if have tested this combo yet?

**Comment by TheZeroBeast** [comment]
I only have the e3d v6 hotend combo sorry.

What issues are you having getting this going? I.E. what changes do you normally do to make it work on stock FW?

**Comment by rmilyard** [comment]
Added Thermistor table for Slice Engineering.

<https://github.com/BondtechAB/Bondtech_Prusa_i3/tree/master/Firmware/3.8.0#mk3s-changes>MK3s Changes

  *   #define CUSTOM_MENDEL_NAME "Bondtech-PE MK3s"
  *   #define DEFAULT_AXIS_STEPS_PER_UNIT {100,100,3200/8,415}
  *   #define Z_MAX_POS 205
  *   #define TMC2130_USTEPS_E 16
  *   #define LOAD_FILAMENT_1 "G1 E80 F400"
  *   #define UNLOAD_FILAMENT_1 "G1 E-95 F7000"
  *   #define FILAMENTCHANGE_FINALRETRACT -95
  *   #define FILAMENTCHANGE_FIRSTFEED 80


________________________________

**Comment by rmilyard** [comment]
My filament tips are stringy.  Also little to big.  They are getting jammed and not loading so have load fail until I cut the tips.

**Comment by TheZeroBeast** [comment]
Thanks for the list of changes.

With the large tips and stringing, have you double checked you have the correct heatbreak and smaller inner diameter extruder PTFE? They are not optional.

I did a test a long time ago with a stock brand new e3d v6 heatbreak and not a single mmu2 load would work. I can't remember the tip diameter measurements but it was a substantial difference in tip size.

**Comment by gizzburn** [comment]
Is the Bondtech BMG on the list to do next Robert?.

**Comment by TheZeroBeast** [comment]
I'll compile and add the mosquito hex to my final release tonight.

**Comment by rmilyard** [comment]
I would be interested also in new Bondtech Mosquito with Slice thermistor firmware.

**Comment by TheZeroBeast** [comment]
Hi @rmilyard, [releases](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases) page now has a build with SE HT Thermistor tables and bondtech changes. Let me know if it works

**Comment by TheZeroBeast** [comment]
Hi @rmilyard, any chance you've loaded the release for Mosquito to confirm it works?

**Comment by rmilyard** [comment]
No. I am in CA with family at Disneyland.

Sent from my iPhone

On Oct 9, 2019, at 5:00 AM, Robert McKenzie <notifications@github.com> wrote:

﻿

Hi @rmilyard<https://github.com/rmilyard>, any chance you've loaded the release for Mosquito to confirm it works?

**Comment by TheZeroBeast** [comment]
Ah sweet! Enjoy, let me know when you return.

**Comment by TheZeroBeast** [comment]
@rmilyard, how was Disneyland, any update on this thread?

**Comment by TheZeroBeast** [comment]
Stale issue thread. It you have any issues please advise so we can re-open and resolve.
