### ISSUE TITLE
Go back to original

### ISSUE THREAD

**Issue by lmyvgta** [TheZeroBeast/MM-control-01#151]
Hi ive installed the latest RC3 ver. I couldn't get to the original prusa firmware. Is there any updates that you can release so i can test both firmwares?

**Comment by TheZeroBeast** [comment]
Hi @lmyvgta,

What do you mean you couldn't get to the original prusa firmware?

**Comment by lmyvgta** [comment]
I couldn't reinstall the Original prusa firmware.  It didn't detect it.

**Comment by TheZeroBeast** [comment]
Wonderful, you can try out the flashing wiki I made last night 👌👏

https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/wiki/Flashing-Procedure

Let me know how you go.

Did you test this firmware at all, or just wanted some stock loving?

**Comment by lmyvgta** [comment]
Ill try, but ive just installed it and had some issues with the lenghts of the filament in the gears, and i didnt have time to set the new parameters. i thought it was easier to go back to stock, but i couldnt go back at all

**Comment by TheZeroBeast** [comment]
Bowden calibration is the same procedure as stock 👍

Can’t get much easier than power and flash.

**Comment by AbeFM** [comment]
> Ill try, but ive just installed it and had some issues with the lenghts of the filament in the gears, and i didnt have time to set the new parameters. i thought it was easier to go back to stock, but i couldnt go back at all

It's pretty trivial. Open door to see gears. Turn on printer, move selector to far right, press middle, left, middle, middle, left/right till adjusted right, middle, left.

That's it.

**Comment by TheZeroBeast** [comment]
Indeed, here's the walkthrough I did up.
https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/wiki/Bowden-Length-Calibration
