### ISSUE TITLE
Rapid flashing LED on filament load

### ISSUE THREAD

**Issue by Canceltodebug** [TheZeroBeast/MM-control-01#163]
**TZB-MMU2S Release Version**
3.0.2

**Describe the bug**
Rapid LED (first light) flashing orange when filament loads to MMU2 or extruder. Bed and extruder continue to reach temp and no error message. Have to press 3rd button to retract filament and then 2nd button to reload. If extruder not up to temp then it will flash orange again.
Seems to me like a feature added since 3.0.1.

**To Reproduce**
Load filament. Seems to be related to when extruder is not up to temp.

**Expected behavior**
No flashing LED and print to start as per 3.0.1.

**Comment by TheZeroBeast** [comment]
Hi @Canceltodebug,

No new features regarding this have been implemented since 3.0.0.
The flashing LED is indicating load error which needs to be cleared before it will continue.

How is it even attempting to load if the hotend isn't up to temp? This is indicating that your start gcode isn't correct.

If by chance you're using the octoprint script that replaces T? with T<n> then this will cause this issue as T<n> requires a preheated hotend, to fix adjust the position of T? in your slicers start gcode to after hotend is heated.

**Comment by Canceltodebug** [comment]
I've rolled back to 3.0.1 and it is working as expected again.
No modifications are being made to the gcode after being sliced with PrusaSlicer 2.1.0.
Not using Octoprint either. Just a standard 'model > slice > print from SD card'.

I will re-install the 3.0.2 firmware again later today but since I'm not changing anything during the slicing process from 3.0.1 to 3.0.2, I don't see if this will help as it sounds like the gcode is being misread somehow? I'm not making any modifications as all.

**Comment by TheZeroBeast** [comment]
Hi @Canceltodebug, I think I found a line that might be causing this issue that crept in with LA1.5 integration. I'll build a test hex tomorrow for you to try.

**Comment by Canceltodebug** [comment]
That's great, thank you.

**Comment by TheZeroBeast** [comment]
[TZB-MK3S-3.0.3-ALPHA-BN2476.hex.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3804086/TZB-MK3S-3.0.3-ALPHA-BN2476.hex.zip)

**Comment by AbeFM** [comment]
does this certain include the changes you wanted me to test yesterday?
Should I run this one instead of what's linked in other thread?

                  Thanks!
                          -Abe.

**Comment by Canceltodebug** [comment]
> 
> 
> [TZB-MK3S-3.0.3-ALPHA-BN2476.hex.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3804086/TZB-MK3S-3.0.3-ALPHA-BN2476.hex.zip)

Loading as per 3.0.1 again. Thank you :)

**Comment by TheZeroBeast** [comment]
@AbeFM this one mate.

@Canceltodebug, did you see if that build helped the lid issue?

**Comment by Canceltodebug** [comment]
Hi @TheZeroBeast 
Yes, it is loading correctly again. Thank you.

**Comment by TheZeroBeast** [comment]
Wonderful, the fix will be apart of the next release, thank you for your help.
