### ISSUE TITLE
Selector blocks manual clearing of failed MMU loads

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#166]
When I get a bad load, or grind plastic in the MMU, generally I can clear it if I can get the Selector out of the way.

The two buttons are dedicated (I believe?!?) to feeding the filament in and out, and pressing the center moves the selector tantalizingly away but it comes right back before you can clear the error.

Perhaps a long press on the buttons could move selector, or the move to the service position could pause in some circumstances.

Not well thought about but the issue has been nagging me since the generally better handling of things that was introduced a while back.

**Comment by TheZeroBeast** [comment]
Hey @AbeFM, in all error states the selector is disengaged to allow manual moving where you please 👍

**Comment by AbeFM** [comment]
Great. Thanks. I knew that. It's not that easy to move, in my opinion. It is much harder to move the selector over 4 slots than it is to pull the filament forward or back.


I was trying to make a suggestion to make the system easier to use. It is a
Big Pain to move the selector around. Perhaps with a redesigned MMU with a
friendly knob for rotating that shaft, otherwise, it sucks.

It might be more productive to consider ways to use the buttons to increase
the usability of the MMU. Like "go to previous temperature" makes it easier
to use - I have not found rewinding or ejecting filament to be nearly as
useful, which is why I brought it up.

I would ask that you reopen the issue so we can discuss how the two options
effect the user's experience.
