### ISSUE TITLE
Integrate G81 Center Relative for Nyloc-Mod as Standard-Behavior in TZB-Firmware

### ISSUE THREAD

**Issue by XRyu** [TheZeroBeast/MM-control-01#171]
What do you think about setting the G81-Center-Relative Behavior as a standard?
This is mostly used by Nyloc-Mod-Users which improves Bed Leveling a ton

https://github.com/PrusaOwners/prusaowners/wiki/Bed_Leveling_without_Wave_Springs

**Comment by TheZeroBeast** [comment]
Hi @XRyu, has this been requested to be pulled into PRUSA stock FW?

**Comment by XRyu** [comment]
No, i dont think so, as its more a thing of the modders and tinkerers to do the nyloc-mod i think :)

**Comment by XRyu** [comment]
Close the issue, someone started making an awesome Octoprint Addon for the process, based on the Stock-G81, so any modifications for this would make this harder in the future :)
https://github.com/scottrini/OctoPrint-PrusaLevelingGuide
