### ISSUE TITLE
mmu security after upgrade to last fw

### ISSUE THREAD

**Issue by FredMk3** [TheZeroBeast/MM-control-01#173]
hi, i don't can use the last 3.0.2 fw because this one make not use good mmu2 because at load print mmu2 load filament on the extrudeur (calibration in center of bondtech ok) but nema of extrudeur make new load filament and this one make stop working mmu2 because of grinding filament.

the only solution is go back to 3.0.0 or 3.0.1 for get working. 

i use this files
TZB-MK3S-3.0.2-BN2472
and TZB-MMU2S-3.0.2-BN362

**Comment by TheZeroBeast** [comment]
Can you please go into further detail on this issue you’re having, I don’t follow.

**Comment by FredMk3** [comment]
Sorry for my bad English.

On the last rev I cannot print.
I make flash mk3 and mmu, I calibrate Bowden (same as previous version) but when I test to print a file, the filament go to extruder and the motor run for approximately 7 seconds and this make out filament inside chamber and blocks it.
The ir sensor see filament, but motor don't stop.
This stop print and I do manually push button on mmu for retract the filament. The ir work great. 
I have test to flash 3 time and same issue.
Return on 3.0.1 work fine. 
In 3.0.1 the filament go to extruder, the motor run 1sec and stop when ir sensor see filament.
And all is ok

i use this files
TZB-MK3S-3.0.2-BN2472
and TZB-MMU2S-3.0.2-BN362

Thanks

**Comment by AbeFM** [comment]
Are you REALLY sure the IR sensor is working well?

https://photos.app.goo.gl/qeCGaoDjEYcVkrec6

**Comment by FredMk3** [comment]
Yes i'm sure and see it in the support menu.
I actually make a 17hours print on 3.0.1 with no issue. 
I have test this afternoon to flash 3.0.2 another bit same issue 🤔

**Comment by TheZeroBeast** [comment]
Hi @FredMk3,

Can you please see if this issue is still present on the release today and advise?

**Comment by FredMk3** [comment]
Yes. I make test this week because I think before I don't have time.

I send you if good or same immediately after.

Thanks

Le lun. 9 mars 2020 à 09:42, Robert McKenzie <notifications@github.com> a
écrit :

**Comment by FredMk3** [comment]
All is perfect sir 😉
Work a charm for now.

Le mar. 10 mars 2020 à 19:50, frederic cabeza <fredcabeza.pub@gmail.com> a
écrit :

**Comment by FredMk3** [comment]
All work a charm now.
Thanks for your work. 

I close this issue. 😉
