### ISSUE TITLE
Prusa just released 3.9.0

### ISSUE THREAD

**Issue by gutschke** [TheZeroBeast/MM-control-01#178]
https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.9.0

This is just a place holder bug to remind you to rebase whenever you get the opportunity. Thanks

**Comment by TheZeroBeast** [comment]
Indeed, on my list.

**Comment by TheZeroBeast** [comment]
Update for to public. I have Rebased and started testing the update to Prusa 3.9.0 Final.

**Comment by gizzburn** [comment]
Nice work Robert..

**Comment by TheZeroBeast** [comment]
@gizzburn, all done mate. Release 3.0.4 has been rebased to 3.9.0
