### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by peacemaker85** [TheZeroBeast/MM-control-01#180]
I can't seem to find the source code for the printer firmware itself. New to github so sorry if i missed it, but i really need it due to a blown thermistor port on my board.

Thanks in advance! :-)

**Comment by kajsilander78** [comment]
If you start clicking from here: https://github.com/TheZeroBeast

**Comment by peacemaker85** [comment]
I've tried checking https://github.com/TheZeroBeast/TZB-MK3S-Firmware if that is what you mean, but that one only has the source that's based on the old 3.9.0-RC1 firmware, not the new one.

**Comment by kajsilander78** [comment]
Not out yet. He have just started with the new version.

**Comment by peacemaker85** [comment]
Uhm, yes it is. https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases  :-)

**Comment by kajsilander78** [comment]
Yes, the mmu firmware is rebased, not the printer firmware. As I understand... ;) Not sure if I'm right.

**Comment by peacemaker85** [comment]
Well i'm not sure either, but the official prusa firmware only updates the printer firmware, and not the mmu firmware, i assumed 3.0.4 was updated to 3.9.0. Oh yeah. Robert also wrote in the release notes that 3.0.4 is rebased to 3.9.0. Sorry if i come ff as a smart ass. I just love this firmware and can't wait to get my MMU to make sense again. :-)

**Comment by TheZeroBeast** [comment]
Hi @peacemaker85, sorry forgot to hit commit on that repo.
https://github.com/TheZeroBeast/TZB-MK3S-Firmware

**Comment by TheZeroBeast** [comment]
When I rebase both MMU and MK3 get rebuild with my latest changes. I release both on the MMU2S release page, at least HEX wise. Source is now committed up 👍

**Comment by peacemaker85** [comment]
Yay, thanks! Keep up the great work!
