### ISSUE TITLE
Updated FW to 3.9.1

### ISSUE THREAD

**Issue by Ruhkukah** [TheZeroBeast/MM-control-01#185]
Hi TZB, I decided to merge changes from your firmware with Prusa's FW 3.9.1. This is my first attempt with Github and I haven't figured everything out yet, so I did it in my own repository: https://github.com/Ruhkukah/Prusa-Firmware/tree/TZB-Full-Ruhkukah-3.9.1. Basically, I took 3.9.1 files and transferred all your changes meanwhile adapting to the new flavor of 3.9.1 (for example, they made many changes that overlap with your code so I made these changes too).

I also included one precompiled binary for MK3S with a stock extruder (it is in the folder "Prusa MK3S Stock - compiled binary").

After the update both MK3S and MMU2S work great, as expected. I am now close to an end of 5-filament print with ~350 color changes and I haven't noticed any issues. Feel free to use it and let me know if there any issues with how I updated the firmware - I am new to this. 

And thank you for your work - I enjoy printing with MMU2S after I upgraded to your FW!

**Comment by Ruhkukah** [comment]
Also, I tried to merge changes to your firmware directly from 3.9.1 but there were too many changes. I ended up modifying 3.9.0 with the code from your FW and then updated changes from 3.9.1 to the modified 3.9.0

**Comment by XRyu** [comment]
@Ruhkukah can you enable issues on your repo too? as it looks you're going to be the spiritual successor of TZB for now ;) 
I would love to see your FW built with the BMG + Mosquitto Magnum + SE HT Thermistor :)

**Comment by Ruhkukah** [comment]
@XRyu done! see here https://github.com/Ruhkukah/Prusa-Firmware/tree/TZB-Full-Ruhkukah-3.9.1/MK3S_Bondtech-16-EINSy10a-SE_HT-Mosquito_Magnum

Let me know your feedback on how it works

**Comment by XRyu** [comment]
Wow that was very quick! :D Which of the two files am i supposed to use - whats the difference with bootloader? :)
Just a thought - how about pulling in the PlatformIO-parts too? Or is it something now wanted, even though it seems to make building easier and faster? :)
Have just seen the PR here in the Upstream repo: https://github.com/prusa3d/Prusa-Firmware/pull/2747

Anyway, i am going to flash today :D

**Comment by Ruhkukah** [comment]
These are two types of files that Arduino exports after compilation. Since I use Arduino to flash my Prusa directly, I don't know exactly which of these two files to use, so I uploaded both of them. Please let me know which one of these works.

Regarding PlatforIO - I may explore it later this week. For now I wanted to keep as close to stock compilation recommendations as possible to minimize any glitches with the FW

**Comment by XRyu** [comment]
Ah alright. Flashing with Octoprint warned me to flash the with_bootloader file, which might corrupt the boards bootloader.
just a question - when the TZB-Firmware was flashed there was the name of the build displayed after starting e.g. "TZB-MK3S-BMGMM" or the like. Now its not :)

**Comment by Ruhkukah** [comment]
@XRyu I am confused. Which file did you end up flashing with - without the bootloader or with the bootloader?
Also, what is the name of the build that is displayed after you start the printer? I can't check mine, since I am in the middle of print

**Comment by XRyu** [comment]
@Ruhkukah I flashed the file without the bootloader :)
And i was wrong (Octoprint was just faster than me having a look) - It shows "Bondtech-MM-TZB MK3s" right after the start.

**Comment by danielalexis** [comment]
@XRyu Hi! i will be updating my repo to include new versions!

**Comment by WarrenSchultz** [comment]
@Ruhkukah  I haven't been set up to build firmware for a while. If I do a pull from your source tree, does it compile MK3S_Bondtech-16-EINSy10a-SE_HT-Thermistor automatically? (If you want to upload the hex for that, I can test if you're not set up to do so, otherwise, I'll set up my environment again.)

**Comment by Ruhkukah** [comment]
> @Ruhkukah I haven't been set up to build firmware for a while. If I do a pull from your source tree, does it compile MK3S_Bondtech-16-EINSy10a-SE_HT-Thermistor automatically? (If you want to upload the hex for that, I can test if you're not set up to do so, otherwise, I'll set up my environment again.)

Hi @WarrenSchultz, not sure that I fully understand your question but here is my take on it: you need to compile a branch found here: https://github.com/Ruhkukah/Prusa-Firmware/tree/TZB-Full-Ruhkukah-3.9.1/Firmware
Since you want to use a **MK3S_Bondtech-16-EINSy10a-SE_HT-Thermistor** configuration, you need to copy an appropriate file from the **variants TZB** folder and rename it to **Configuration_prusa.h**. Follow instruction to compile a firmware from [https://github.com/prusa3d/Prusa-Firmware](url). Let me know if something is not clear

**Comment by WarrenSchultz** [comment]
@Ruhkukah 
> Hi @WarrenSchultz, not sure that I fully understand your question but here is my take on it: you need to compile a branch found here: https://github.com/Ruhkukah/Prusa-Firmware/tree/TZB-Full-Ruhkukah-3.9.1/Firmware
Thanks for the tips, ran into an issue with paths on the precompiled binaries causing git to not like pulling down to WSL, so I'm looking for a way around that, but if it's something you can fix on your side, you might want to for anyone else. 
Thanks again


![image](https://user-images.githubusercontent.com/8450968/100013077-41fd4000-2da2-11eb-915d-2d5727842e1d.png)

**Comment by TheZeroBeast** [comment]
Hey guys, sorry, just saw this thread. I’ll rebase to 3.9.2 on printer FW this week for us 👍

Incoming, I have some time off shortly sorry guys.

**Comment by TheZeroBeast** [comment]
Hi guys, now rebased upstream to 3.9.2, check it out [here](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases).
