### ISSUE TITLE
Please add a variant for MK3S Bondtech Mosquito SE HT Thermistor

### ISSUE THREAD

**Issue by viper2g1** [TheZeroBeast/MM-control-01#189]
On the supported printers section of the firmware releases page there is no specific configuration for an MK3S with Bondtech, Mosquito, and a Slice HT Thermistor.  

There is a similar option for the Bondtech, Mosquito Magnum, and the Slice HT Thermistor.  

I do not know if those are interchangeable since there are specific different versions for the following:

MK3S Bondtech Mosquito
MK3S Bondtech Mosquito Magnum

Please add a variant for:

MK3S Bondtech Mosquito & SE HT Thermistor

**Comment by TheZeroBeast** [comment]
Hey, I'll see if there's much difference with the magnum config and get it added mate.

**Comment by TheZeroBeast** [comment]
I've added this into the next release which is immanent.
Testing is happening this week to check on #192 issue then release.

**Comment by TheZeroBeast** [comment]
[Resolved in Release 3.2.0](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases/tag/3.2.0)
Please comment if you have any questions.
