### ISSUE TITLE
thermal protection

### ISSUE THREAD

**Issue by sergiofagundes** [TheZeroBeast/MM-control-01#190]
**Describe the solution you'd like**
Check that the temperature is actually increasing when a heater is on. If the temperature fails to rise enough within a certain time period (by default, 2 degrees in 20 seconds), the machine will shut down with a “Heating failed” error. This will detect a disconnected, loose, or misconfigured thermistor, or a disconnected heater.

Today I was initiating a printing and the temperature of the hotend stopped at 200C (where I have setup for 235C), and I looked the nozzle dripping the filament like boiling watter (lol)... I imediattely shutdown the printer and to check a bad connection of the thermistor.

So I opened the settings of the firmware for something to protect this to happen, but didn't find a solution. I know Marlin has 2 types of protection in firmware (I use both in my delta printer), but in Prusa it's missing theses settings:

#define WATCH_TEMP_PERIOD
#define WATCH_TEMP_INCREASE
#define WATCH_BED_TEMP_PERIOD
#define WATCH_BED_TEMP_INCREASE

I'm writing to ask if it's possible to add this feature in the TZB firmware.

Thank you

**Comment by TheZeroBeast** [comment]
Sorry mate, this is something I'm going to leave to the parent firmware if not addressed as you say.
