### ISSUE TITLE
M112 with Octoprint on MMU Single Mode

### ISSUE THREAD

**Issue by XRyu** [TheZeroBeast/MM-control-01#194]
Hey TZB, can you have a look if you lost some part in the firmware regarding the Octoprint causing M112? 
I have these more often lately when printing in Single Mode - 
Its mentioned here on 3.9.1 (last point in 3.9.1): https://github.com/prusa3d/Prusa-Firmware/releases

**Comment by TheZeroBeast** [comment]
M112 issue will be all fixed in my next release as it’s rebased to stock 3.9.3

**Comment by TheZeroBeast** [comment]
How often are you getting the error?

**Comment by XRyu** [comment]
I made 4 attempts yesterday, had 2 times the problem, after having it and resetting the printer it
works. i think it has something todo with the printer waiting for new
commands from octoprint and octoprint waiting for the printer to warm up.
after the reset and reconnection it wont take as log to heat up.

I will try to flash to the new version tomorrow :) so much thanks for your
work! :D

Am Fr., 22. Jan. 2021 um 04:40 Uhr schrieb Robert McKenzie <
notifications@github.com>:

**Comment by TheZeroBeast** [comment]
Hey @XRyu, did you get a chance to try this out on the latest release of my code?

Also, this is my list of octoprint long running commands, it may play a roll in this error and stopping it.
`G4, G28, G29, G30, G32, G80, M400, M226, M600, M860, M190, M109, M701, M702`

**Comment by XRyu** [comment]
Hey @TheZeroBeast, thank you!
After installing the latest release with my first testprint everything worked :)
Sadly i had an incident, got a jam in the heatbreak of my Mosquito Magnum with Prusa PLA, so i had to disassemble etc. When re-assembling i seemingly took to much force, broke the Bondtech Shaft Gear :'D Had to order replacement, after that i also seemed to have broken my HT-Thermistor somehow (MINTEMP) - again - replacement ordered and installed - first day back working today :) As far from now it looks good, error stopped :)

**Comment by TheZeroBeast** [comment]
@XRyu, 

Annoying when a bunch of failures happen at once but glad you're now back up and running.
