### ISSUE TITLE
Multi Language build

### ISSUE THREAD

**Issue by fila612** [TheZeroBeast/MM-control-01#198]
Hi TZB,

is it possible to build your release with multi language support?
i'm not an expert but it seems that should be possible using the Prusa files e.g. "lang" folder.

maybe i can help you, if i can ;)

thanks

**Comment by TheZeroBeast** [comment]
yep, possibly, I haven't had any luck trying before, I'll try and see what hurdle appear.

**Comment by fila612** [comment]
Thanks,
Same here,
Got some Compiler errors and i have no idea to fix them.

**Comment by TheZeroBeast** [comment]
Stale issue, closing.
If anyone wants to get this working I would welcome a PR, otherwise I do not have the time to put into this.

Anyone can build their own hex with desired language.
