### ISSUE TITLE
New Prusa Firmware version 3.10.0

### ISSUE THREAD

**Issue by timemaster5** [TheZeroBeast/MM-control-01#204]
@TheZeroBeast, I remember you said some time ago that notifications didn't work well for you, so this is just a note about the Prusa Firmware version 3.10.0. No rush, and thank you for the great work!

**Comment by XRyu** [comment]
I would also love to see that updated @TheZeroBeast  :D Looking forward to this :3

**Comment by Naugrimohtar** [comment]
@TheZeroBeast Do you have anything setup for donations to help you with your time and efforts?

**Comment by gutschke** [comment]
There is a "Donation" button on https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases

I have occasionally sent the author a token of my appreciation, hopefully he was able to get himself all the coffee that is needed to power his amazing work ;-)

**Comment by TheZeroBeast** [comment]
I do get myself a coffee from time to time, thank you for your support.

I have been working on rebasing and fixing some bugs but have a hurdle with my development environment not compiling after an update🤦‍♂️

**Comment by TheZeroBeast** [comment]
I'm testing a version rebased to PRUSA 3.10.0 now I have my development environment behaving.

**Comment by TheZeroBeast** [comment]
Please enjoy, 3.3.0 is out. Any issues please document and post, I'll endeavour to resolve as soon as possible.
