### ISSUE TITLE
Bowden Length Calibration

### ISSUE THREAD

**Issue by Ondak87** [TheZeroBeast/MM-control-01#207]
Printer type - MK3S+
Printer firmware version - TZB-MK3S_EINSy10a-3.2.0-BN2495
MMU2S
MMU upgrade firmware version - TZB-MMU2S-3.2.0-BN371
extruder - TZB MK3S MMU2S (No Tower)

Describe the bug
When bowden length calibration is new value doesnt change position ,,1,, bowden length calibration are change only for ,,2-5,,.

Expected behavior
Bowden Length Calibration are change on new value for ,,1-5,,.

**Comment by TheZeroBeast** [comment]
Hi @Ondak87, can you please provide more details and all the steps you came to your conclusion so I can attempt to troubleshoot?

**Comment by Ondak87** [comment]
Hello @TheZeroBeast, i'm sorry, I did a new bowden calibration test  and problem was in MMU board.

Tiket you can closed
