### ISSUE TITLE
Mmu2s and Display

### ISSUE THREAD

**Issue by Ondak87** [TheZeroBeast/MM-control-01#215]
Hello @TheZeroBeast 

Do you try work on modifying your SW on the mmu2s board and add a display as is the case with mmu 12x from cjbaar?

Advantage:
Only aesrhetically diesan

Thank you

**Comment by TheZeroBeast** [comment]
Hi @Ondak87, I do like the 12x design by @cjbaar but I don't have the time or funds to implement this with my code.
If you or someone else has the the setup and is willing to code I can offer guidance.
