### ISSUE TITLE
Z Axis movement shortcut

### ISSUE THREAD

**Issue by dameningen4914** [TheZeroBeast/MM-control-01#216]
Hello TheZeroBeast.
I am very happy that your firmware has been updated. 

However, I have one request.

the original Prusa firmware, I can move the Z axis by long pressing the function button.
But your 3.3.0 firmware doesn't have that feature. 

Can you add this shortcut function?

Thank you.

**Comment by BaconFase** [comment]
I've also noticed this feature loss. 3.0.4 had this function.

**Comment by Naugrimohtar** [comment]
I too have noticed this feature loss, a feature I used very heavily actually.

**Comment by timemaster5** [comment]
+1

**Comment by fromanza** [comment]
+1

**Comment by timemaster5** [comment]
I submitted a [PR#29](https://github.com/TheZeroBeast/TZB-MK3S-Firmware/pull/29)

**Comment by TheZeroBeast** [comment]
I also noticed this recently and believe the PRUSA RC has fixed it, I'll rebase in the near future.

**Comment by TheZeroBeast** [comment]
Fixed in Release 4.0.1 happy holidays.
