### ISSUE TITLE
Can Load to nozzle but failed loading in printing

### ISSUE THREAD

**Issue by sergiofagundes** [TheZeroBeast/MM-control-01#217]
Ensure you're running the latest **RELEASE** and you've checked the **Wiki** for answers before reporting. Any issues reported regarding previous **RELEASES** will automatically be closed and not responded to, this ensures the developer maintains focus & streamlines the development process.

**TZB-MMU2S Release Version**
3.2.0-371

**Describe the bug**
I can load/unload to nozzle filament. But if I print any file, the printer loads the filament in the beginning, make a leveling bed and homes. At this time the filament is not feed to the nozzle, the process is repeated if unloading/load several times and not complete.

I only changed the firmware from TZB3.2.0 to TZB3.3.0.

I have a prusa with not original prusa motors so my tmc current settings settings and stallguard settings are a little changed, but have worked with all TZB firmware versions, but not with 3.3.0.

**To Reproduce**
1. Load/Unload filament to/from nozzle OK
2. Printing keeps trying to Load filament to begin printing, the filament gets caught by the gears succesfully but at time to feed to nozzle and begin printing it failed and unload again to try forever.

**Additional context**
This is not a bug, but I lost in where I should change the tmc settings to get it pass printing process. I think it's a stallguard config to the extruder, but I don't know to to fine tune it to work with the new version 3.3.0.

**Comment by TheZeroBeast** [comment]
Hi guys, this is under investigation. I'll let you know how I go.

**Comment by TheZeroBeast** [comment]
Hi @sergiofagundes,

I haven't uncovered any more on this issue, can you please try the latest release and let me know how it goes?

**Comment by TheZeroBeast** [comment]
@sergiofagundes, I'm closing this as I haven't had any response in months. If you're still having issues on the latest release please reopen or open a fresh issue.

**Comment by 10bn** [comment]
I'm running into the same issue right now with the latest firmeware. Anything I can provide to debug this?

The second light of the mmu from the left is flashing rapidly after this.
