### ISSUE TITLE
Selector loses position 

### ISSUE THREAD

**Issue by madxbgt** [TheZeroBeast/MM-control-01#219]
Ensure you're running the latest **RELEASE** and you've checked the **Wiki** for answers before reporting. Any issues reported regarding previous **RELEASES** will automatically be closed and not responded to, this ensures the developer maintains focus & streamlines the development process.

**TZB-MMU2S Release Version**
The version of the release relating to the bug report.
3.3.0- 375
**Describe the bug**
After an unload failure is rectified, the selector ignores the position until the printer is shutdown completely. 
In this case I had been printing with T0 and T1 the unload failed on T1, after fixing the issue, the selector starts using T2 instead of T1.  Even if I restart the print, even after a reset, T1 is ignored all together and T0 and T2 is used. The only way to rectify the issue is a power cycle.  I can move the selector to each position manually after a reset, but under gcode the last tool that failed is ignored.
**To Reproduce**

**Expected behavior**
Obviously expect it to return to T1 again
**Screenshots**

**Serial Log**
Please attach and serial logs of this issue.

**Additional context**

**Comment by TheZeroBeast** [comment]
Hi @madxbgt, I have been investigating a few issues and think I know what is happening here and I have a strong suspicion it is AutoDeplete stuffing us.

I will go through and test this feature and most likely find and fix this bug.

**Comment by TheZeroBeast** [comment]
[This Commit](https://github.com/TheZeroBeast/TZB-MK3S-Firmware/commit/1bbcc9a409784164a0932a8646006594ce96a545) should resolve this issue, pending testing.

**Comment by TheZeroBeast** [comment]
Hi @madxbgt, I think I have this sorted now with some further testing. I found an issue with the auto deplete implementation that would mess up available extruders when not even enabled in menu.

**Comment by TheZeroBeast** [comment]
Please review [4.0.2](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases/tag/4.0.2) release and re-open if your issue persists.
