### ISSUE TITLE
Implement ArcWelder support PR

### ISSUE THREAD

**Issue by WarrenSchultz** [TheZeroBeast/MM-control-01#221]
While we wait for Prusa to implement support for proper arc support, would you be willing to merge in the PR that's waiting on their approval on the main codeline?

https://github.com/prusa3d/Prusa-Firmware/pull/2657

**Comment by TheZeroBeast** [comment]
Hi @WarrenSchultz,

This looks interesting, I will investigate.

**Comment by TheZeroBeast** [comment]
Hey @WarrenSchultz, I have been down this path in the past and from taking a look again I feel there still isn't a big enough advantage to put time and effort into merging this into my forked print codebase. I will be waiting for PRUSA to merge and then I'll update.

**Comment by WarrenSchultz** [comment]
No worries, @TheZeroBeast  thanks for taking a look!
