### ISSUE TITLE
Questions: Compiling from source

### ISSUE THREAD

**Issue by fromanza** [TheZeroBeast/MM-control-01#231]
Perhaps a stupic question but I've downloaded your source & loaded into PlatformIO but when I compile I get a significantly different .hex file sizes which I assume cant be a good thing. PlatformIO reports "MMU2S-TZBDualBlade  SUCCESS". The file you compile in your git repo is 49KB and the one I compile is 61KB (attached for reference). Is there compression happening or is my version going to introduce some 'odd' behaviour...AKA it work work...

Second question is, where or how is the "TZB-MK3S-4.0.2-BN2528.hex" code handled, I dont see any up to date source for this? Are the majority of the changes and control within the MMU2S firmware?

Thanks! Respect for your work!

[TZB-MMU2S-Firmware-4.0.2.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/8553362/TZB-MMU2S-Firmware-4.0.2.zip)

**Comment by TheZeroBeast** [comment]
Printer source is [here](https://github.com/TheZeroBeast/TZB-MK3S-Firmware)

If you haven’t added that line at the top of the file maybe.
If it’s successful then it should work fine 👍
