### ISSUE TITLE
Readme.md needs rework

### ISSUE THREAD

**Issue by bryn51** [TheZeroBeast/MM-control-01#232]
I can happily build this code using Platformio, within VS Code, on my Mac.

But the instructions found in readme.md make no sense at all.

Build instructions:
download the code base zip file and open it in your file system.  This creates a folder containing src folder.  Platform.ini is found at the base.
Start VS Code, and open the folder that was created when you unzipped the download.
Open the project at the base folder that contains platform.ini
click on the platformio button (little face icon).
Select either the MMU2S-TZBDualBlade option or the MMU2S-DoubleCutter option, depending on which hardware you already printed and installed.  Open the 'General' menu option
Click the build button in that option.
The Terminal window opens on the main screen and you see progress of building which happens pretty quick.
it should say at the end:
>>>
RAM:   [==        ]  15.5% (used 398 bytes from 2560 bytes)
Flash: [======    ]  61.9% (used 17754 bytes from 28672 bytes)
Building .pio/build/MMU2S-TZBDualBlade/TZB-MMU2S-TZBDualBlade-4.0.2-BN380.hex
 [SUCCESS] Took 1.02 seconds 

Environment         Status    Duration
------------------  --------  ------------
MMU2S-TZBDualBlade  SUCCESS   00:00:01.016

>>>

The file TZB-MMU2S-TZBDualBlade-4.0.2-BN380.hex constitutes the operational firmware code that needs to be installed into the MMU MCU device, which can be done using PrusaSlicer with the MMU plugged into an available USB-A port on your computer.  This means that if you have a MacBook you are going to need a dongle to provide USB-C to USB-A conversion.

Thats OK so far as it goes, but whats not clear are the instructions :
The HEX which is placed within the .pio root folder still requires the addition of the the bellow line.
~~~
; device = mm-control
~~~
This extra Line needs to be added to the top of the file.  If not added then the upload to the device will fail.

Revised instructions are needed.  The readme file needs to be updated with more details somewhat similar to what I have given above, to guide less experienced people that may not be confident about building code files.

**Comment by TheZeroBeast** [comment]
Duplicate to #223
