### ISSUE TITLE
Request: Changes needed to disable steppers on MMU after timeout

### ISSUE THREAD

**Issue by sabaatworld** [TheZeroBeast/MM-control-01#236]
I really like the feature which disables the MMU after a timeout to avoid static noise. Can you please point me to the changes you've made to accomplish this? I'm trying to do the same on stock firmware.

**Comment by TheZeroBeast** [comment]
Hi @sabaatworld, main.cpp line 172 is where I initiate the timeout using the enable lines on the steppers via the shift register.
I haven't looked recently at stock code but I needed to make changes for the shift register code for it to make sense and be usable for my needs.
