### ISSUE TITLE
Available for MK2.5? 

### ISSUE THREAD

**Issue by SkyDriver2k4** [TheZeroBeast/MM-control-01#27]
Hi, will this work for the MK2.5 as well?

**Comment by JohnOCFII** [comment]
> Hi, will this work for the MK2.5 as well?

According to the notes, the answer is yes.

"Building this custom setup

This is configured to work directly with MK2.5/MK3 with matching printer FW at link below to load filament to ExtruderLaserFilamentSensor and unload to FINDA Sensor."

**Comment by SkyDriver2k4** [comment]
Hi John, the firmware linked seems only for the MK3 :)

**Comment by TheZeroBeast** [comment]
No work has been done on MK2.5 yet and I'm not in a position to in the near future. If someone is able to in the community please be my guest.

**Comment by SkyDriver2k4** [comment]
Sadly i can't. Don't know what to change to make this work with 2.5 Firmware. Thanks for your work

**Comment by TheZeroBeast** [comment]
Hopfully early next year I'll make a clone for my MK2.5 and I'll dev.

**Comment by tito2018** [comment]
@TheZeroBeast what would you need as far as hardware goes to be able to work on the MK2.5 version? I can try to get some parts together to get you going.

**Comment by TheZeroBeast** [comment]
thank you for the offer but I'd still need steppers and their associated hardware, mmu2 board & ballbearing.
I have ability to mkae the y-harness and have old pinda on hand.

Any case, I'll have to save and source when I can.

**Comment by AbeFM** [comment]
You'd need the pcb and stepper with long shaft - and the five bondtech's. Several people have a spare set of poorly matched ones to donate of that comes up.

**Comment by TheZeroBeast** [comment]
Not planned for current future.
