### ISSUE TITLE
Reco vering from misload, temperature not accurate

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#30]
Pressed button on mk3, temp starts ticking up. Pressed button on MMU, fed filament down to printer - without response.

Printer read 220/245 degrees for many minutes without changing. Upon reset, temp read ~241 degres and falling, as if display was frozen before reset.,e

**Comment by TheZeroBeast** [comment]
Hi AbeFM, was this when using the menu load to nozzle?

**Comment by TheZeroBeast** [comment]
no response.

**Comment by AbeFM** [comment]
That was during a failed load on a filament switch. At this point I'm not even totally sure which firmware, I'm guessing MP1

**Comment by TheZeroBeast** [comment]
All good 👍
