### ISSUE TITLE
Middle button behaviour

### ISSUE THREAD

**Issue by danielegger1** [TheZeroBeast/MM-control-01#32]
With pressing the middle button I can insert the filament into the mmu but if I do not have a filament ready I cannot abort the loading with the middle button.

Is that supposed to be like that or did I lissed something?

**Comment by TheZeroBeast** [comment]
Yes, it is supposed to be like that. Load with middle button tries three times then stops trying so if you tried to load a channel with middle button that doesn't have filament you can press the middle button again two cycles to clear.
I am changing this to one retry only in the next release.

As per README.md when in error state, e.g. flashing.
Middle button is clear (retry or clear depending on fail position)
