### ISSUE TITLE
Filament runout can cause issues

### ISSUE THREAD

**Issue by danielegger1** [TheZeroBeast/MM-control-01#33]
I am not sure if I should also report such issues to you, as Prusa is doing nothing at MMU firmware I hope you will correct issues ;).
1. issue:
So I had a filament runout and the filament was moved back but I was not able to get the filament out of the tube. In this case the filament needs to move forward to get it out.
2. issue:
I loaded the new filament into the mmu but adter that the mk3 firmware got stuck and I wasn‘t able to continue. This bug is a little bit hard to describe but with several tests this can be easily checked from a programer ;)

**Comment by TheZeroBeast** [comment]
Please specify on which version of my code you're having issues

**Comment by danielegger1** [comment]
Surely on the latest ;)

**Comment by TheZeroBeast** [comment]
Fixed eject methods and tested and working in latest 2.1.5 commit.
