### ISSUE TITLE
Resume after unload fail

### ISSUE THREAD

**Issue by madxbgt** [TheZeroBeast/MM-control-01#36]
Had an unload fail where the FINDA ball bearing was stuck, when I cleared the bearing and restarted the MMU the selector went to the incorrect filament No. it was on F4 and should have continued to F3 but resumed at F2, from then on it was one position out on the selected filament.

**Comment by TheZeroBeast** [comment]
Please try release candidate, a lot of logic issues have been resolved now.
available here: https://github.com/TheZeroBeast/MM-control-01/releases
