### ISSUE TITLE
Length Tuning doesn't move filament - reposition Drum

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#39]
Perhaps you've fixed this in the new version, it was certainly a problem since leaving V0.9.

When I make adjustments to the filament position during the bowden length cal, the drum isn't riding the filament in question.

That makes the adjustment blind since the filament doesn't move, only cycling the filament will show you the result. The other issue is the neighboring filament can extrude while the adjustment is being made, causing crashing when you attempt to go to the next channel.

Appologies if it has already been fixed. If not, I assert we should HOLD the drum on the filament the entire time the filament is being calibrated.

**Comment by TheZeroBeast** [comment]
No longer an issue, just double checked 👍
