### ISSUE TITLE
Selector Not Homing on reboot

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#40]
When I reboot the MMU, the drum will home (quieter now), but the selector just stays put. On first movement, the selector moves and homes.

504TBZ2324//215-555

This means calibrating Bowden length can only really be started with the selector already in position 1, I think.

**Comment by TheZeroBeast** [comment]
Hi AbeFM,

The selector only homes when it needs due to PowerPanic support.

When entering the service menu either way the mmu2 will full home if it isn't already.
