### ISSUE TITLE
Update Docs - only cal one bowden length

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#41]
Just so people know not to freak out, you could mention in the docs that you only set the bowden length once, I was expecting to have to do every channel

**Comment by AbeFM** [comment]
My previously stored value (from the 214-228 release) seemed to be right, I didn't need to update the cal.

**Comment by AbeFM** [comment]
Also, update the docs:
Load/Unload and MMU Parameters should be set in Slic3r to minimize GRINDING.

Could you give some ideas here - what variables, what values? If it's the same as shown below, say so explicitly and if not say what it is.

**Comment by TheZeroBeast** [comment]
Thank you, good idea, this has been updated in README.md now.
