### ISSUE TITLE
Loading doesn't work

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#43]
Every time the printer tries to do a filament change, the filament is unloaded, then the new filament is not fed.

If I don't have all the filaments pre-loaded, the rehoming fails and the drum ends up near/at the homing location.
If I DO have them loaded, it homes correctly and goes to correct filament, but then doesn't see it at the sensor.

Not sure how to help with this - perhaps serial logs?

**Comment by AbeFM** [comment]
I suspect the printer isn't responding to the MMU with it's "filament received" status when in error mode. Not based on anything, just a whisper in my ghost.

**Comment by TheZeroBeast** [comment]
Hmm, I haven't had this where the sensor isn't responding.

If you could get the serial log and the toolChange number it happened on I can take a deeper look.

**Comment by AbeFM** [comment]
If it keeps happening, I will!

So far, reducing he parking distance seems to have fixed it.

**Comment by TheZeroBeast** [comment]
👍 sounds good.

**Comment by TheZeroBeast** [comment]
Duplicate to #44
