### ISSUE TITLE
Bring Back the Blade!

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#45]
I know there's some crow for me to eat on this one, but really, in running MP-1 for a month, I'm sold on the filament cutting. It works really, really well. All sorts of stuff that doesn't feed the first time feeds just great after a cutting.

I'm not sure how it fits into your world-view of MMU operation, but the routine you had never steered me wrong.

**Comment by TheZeroBeast** [comment]
In my experience I never got a load with a sharp edge, it would catch just after fsensor before bondtech gears.

Feel free to fork and add it back in for a personal build. 👍

**Comment by AbeFM** [comment]
Oh yeah, things are a mess in there. I'd go with one of the indirect sensor mods.

Other than smashing two sensors (!), I really found the cutting to work well. I originally had the same concerns, that the blunt tip wasn't super useful, but over the past couple of weeks I've had it work many hundred times without issue, and I don't think any failures.

The other issue I get is filament creeping too far out and catching the selector at random times.

It does seem it would hold back your testing to put it back in. Is it as simple as commenting a line of code? Can  you point me to where?

**Comment by TheZeroBeast** [comment]
I had a sensor smash a couple days ago but from me accidentally putting pressure on the glass 🤦‍♂️

We should make a good extruder mod that allows smooth pass through of a sharp edge filament 👍

**Comment by AbeFM** [comment]
Iv'e seen a bowden-tube-with-notch-for-sensor that seems reasonable, and the indirect sensor seems reasonable (and protects sensor).

I guess I need to try designing one with a grooved pulley, I think it's much less of a blockage.

**Is adding cutting back as simple as commenting a line of code? _Can you point me to where?_**

**Comment by TheZeroBeast** [comment]
to add it back you would need to splice in that section of code from MP-1, from memory it would have to be placed in method fixTheProblem() and then you would need to ensure it works nicely i.e. in each case the method is called, is it the right time to attempt a cut and so on.

**Comment by AbeFM** [comment]
Not worth that much to me. Or more correctly, I couldn't keep it current and still support this development.

Putting it back on the Features Request list is right, and we can talk about it from that perspective. :-)

**Comment by Mjankor** [comment]
The "good extruder mod that allows smooth pass through of a sharp edge filament" has been done. You can feed anything you like into my indirect sensor modded extruder. You won't harm the sensor. The filament pathway is very constrained, and very smooth. 
https://www.thingiverse.com/thing:3223513

**Comment by kmshort** [comment]
AbeFM. I'm about to do the extruder sensor mod myself, as posted above. If cutting works as well as you say it does, I'd be interested in a ZeroBeast firmware with cutting in it.

**Comment by AbeFM** [comment]
I'm not involved with the project. I asked for an explanation of how it worked and it was never made clear. I would love to hear your experiences in detail, someday.

**Comment by AbeFM** [comment]
I would like to keep this thread on topic - using the original blade to cut filament which doesn't load.

I still find filament misloads at times, and the MMU is hung at a point where I would otherwise find the cutter to have been used and the print to still be running. Still not pressing, but still true.

**Comment by TheZeroBeast** [comment]
Still not a good feature to have IMHO.
