### ISSUE TITLE
Calibration Question

### ISSUE THREAD

**Issue by RJ-Make** [TheZeroBeast/MM-control-01#48]
I've read the readme file and perhaps I'm being a bit dumb today. When I enter service mode and attempt to calibrate F1, it pulls it in, then when I press the button again it extracts it.  Repeat and rinse over and over again not adding any length. (I have 600mm clear bowden tube) 

How to I get the filament to the extrude?

**Comment by TheZeroBeast** [comment]
Hello,

It is a cal for tube end, you detach @ Bowden end, adjust to end of tube then (when in an unloaded state) you use left button to save & exit service menu.

It isn’t designed to extrude anything.

To do that you would heat nozzle then use load to nozzle menu on mk3.

**Comment by RJ-Make** [comment]
LOL, Sorry about that, Extrude was an incomplete word. What I meant was How do I get the filament to the extruder.. :-)  My bowden is ~600mm long.

> It is a cal for tube end, you detach @ Bowden end, adjust to end of tube then (when in an unloaded state) you use left button to save & exit service menu.

I have no idea what you mean. how do I "adjust to end of tube.." ?

**Comment by TheZeroBeast** [comment]
Ah, all good 👍

600mm, I might have to increase or remove the cap 🤔

You use left to increase and right to decrease when it’s loaded in calibration.
To get there you’d have to hold left for quite some time to get to 600 I’d say. Report how you go

**Comment by RJ-Make** [comment]
It doesn't work. I guess I'm hitting a limit, as it will retract, but will only move forward to original length. This is the problem that I ran into with the stock FW. 

I'm happy to report this version does not have the same homing problems that I encountered on the prev. version. So progress.. (there is still a unique homing issue that I found, I will start a new thread for that one. )

**Comment by RJ-Make** [comment]
Anyway... I would say remove the cap, It doesn't make any sense to me why it's even necessary, which will probably become painfully obvious once it's removed.. :-)

**Comment by TheZeroBeast** [comment]
I’ll remove that cap on a new rc 👍👌
I’m busy today so it won’t be until later tonight I’d say. 14h I’d guess.

**Comment by TheZeroBeast** [comment]
Before starting another one just check you’re using the code I uploaded on release page last night. There was a idler alignment issue I found.

**Comment by RJ-Make** [comment]
I was using the latest, downloaded this morning. Thanks for all the help and hard work, I look forward to trying the new 'limitless' version.. :-)

**Comment by AbeFM** [comment]
The cap is there to protect people with short tubes, right? Worth a version, but not in the main branch?

Also: I haven't calibrated my length that way. For instance, my bowden goes PAST the sensor.

I calibrate to one step shy of the mid-point of the gears. Should I not?

**Comment by TheZeroBeast** [comment]
#### PLEASE DO NOT DO IT LIKE THAT AbeFM.
Only to the end of the tube when detached from extruder. It wouldn't be using the FSensor at all in that case and then pushing way too much into extruder and most probably grinding filament.
Also, there is no need to have a cap, the only way to get a high value is if you set it.

It's getting blown to just shy of variable limit witch is about 2.8m.

RJ-Make, I just did the change prior to heading out, I'll push it when I can and let you know.

**Comment by AbeFM** [comment]
Wow ok RTFM moment?

Um, **thanks**. I've been having inconsistent behavior and a lot more grinding. I'll go do that now. :-(

So the "end of the tube" is just some point arbitrarily above the filament sensing point? Aim for.... ~5-10 mm? I'm assuming it's used as a "when to turn on sensor" point?

**Comment by TheZeroBeast** [comment]
Should help a lot 👍

Yes, it's where sensing is started.
Detach Bowden tube from extruder and flush with end of tube.

**Comment by TheZeroBeast** [comment]
Hey RJ-Make,

Check out RC3, it has max Bowden untapped for you man 👏👍
https://github.com/TheZeroBeast/MM-control-01/releases/tag/2.1.5-RC3

**Comment by RJ-Make** [comment]
> 
> 
> Hey RJ-Make,
> 
> Check out RC3, it has max Bowden untapped for you man 👏👍
> https://github.com/TheZeroBeast/MM-control-01/releases/tag/2.1.5-RC3

I WORKS!.. This is the first time I've been able to use the MMU since I got it (2 months?).. I'm just using it as a filament selector for now, but who knows I might try a multi-material print one day.. :-0

Thanks for your hard work!

**Comment by TheZeroBeast** [comment]
Excellent, glad it’s now working for you 👍
