### ISSUE TITLE
Idler homing very aggressive

### ISSUE THREAD

**Issue by madxbgt** [TheZeroBeast/MM-control-01#52]
Since the new MM-control RC's the idler homing seems to be very aggressive hitting on the end stops, for around 2 to 3 seconds, not sure if this is as intended.  
Also not sure if this is related but the purge block after flashing to the new RC's is pushing a lot of filament out when starting the wipe a very large blob, slicer settings havent changed, only the firmware, was going to flash back and see if this was the cause.

**Comment by madxbgt** [comment]
Ok sorted out the issue with the purge block my calibration was off so it was loading way past where it should have and forcing into the hot end on loading, this is due to my bowden length being much shorter by about 15mm as I am using a pass through push fitting connector at the extruder, doing away with the short ptfe tube.

**Comment by TheZeroBeast** [comment]
Hey madxbgt, I'll put that setting back, I changed it very slightly but the latter is better for a wider range of MMU2 is seams.

**Comment by TheZeroBeast** [comment]
Hey mate, try RC4, I reverted that to RC1 value.

**Comment by madxbgt** [comment]
Thanks mate that fixed it
