### ISSUE TITLE
MMU2 Single filament mode - unload filament needs cooling move

### ISSUE THREAD

**Issue by diomark** [TheZeroBeast/MM-control-01#53]
Had a fairly long print using a single color (selected filament at the time of print) - printed fine, but failed on unloading. I forced it out, but it was difficult to pull out and actually took the short ptfe tube at the top of the extruder out with it. (the head of the filament was much larger then normal.. I guess from sitting in the hotend..)

Might get past this issue by having a few cooling moves before ejecting the filament? Is that possible?

**Comment by TheZeroBeast** [comment]
This I would say is a Slic3r setup thing.
For single prints I have the following end gcode and I think it is the stock end gcode.
It does a bunch of cool moves in it, see the -10, 10mm extruder moves?


```
G1 X0 Y25 F7200
G1 E2 F5000
G1 E2 F5500
G1 E2 F6000
G1 E-15.0000 F5800
G1 E-20.0000 F5500
G1 E10.0000 F3000
G1 E-10.0000 F3100
G1 E10.0000 F3150
G1 E-10.0000 F3250
G1 E10.0000 F3300

M702 C

G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
; Lift print head a bit
{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up
G1 X0 Y25; home X axis
M84 ; disable motors
```
