### ISSUE TITLE
Printer fails to continue after purge lines

### ISSUE THREAD

**Issue by madxbgt** [TheZeroBeast/MM-control-01#55]
Printer fails to continue after loading filament and printing the first purge lines on the build plate started from RC 3 and RC 4, flashing back to pre RC fixed the issue, then reflashed to RC 4 again issue remains.
Log file attached
[Recv.pdf](https://github.com/TheZeroBeast/MM-control-01/files/2682435/Recv.pdf)
![20181215_160609](https://user-images.githubusercontent.com/45223966/50039825-c908f000-0084-11e9-911b-6e55939f9a8b.jpg)
![20181215_160559](https://user-images.githubusercontent.com/45223966/50039826-c908f000-0084-11e9-8b7f-7b0c82003c27.jpg)

**Comment by madxbgt** [comment]
Update......... Flashed to RC2, issue isn't present

**Comment by TheZeroBeast** [comment]
Hey mate,

Could you please try the following before I update the Releases page?
Hopefully it'll fix this issue for you and anyone else that might come by it.

This is the MK3 side, you would use the MMU2 Latest TZB Release.
[MK3-5.0.4-TZB-BN2328.hex.zip](https://github.com/TheZeroBeast/MM-control-01/files/2683434/MK3-5.0.4-TZB-BN2328.hex.zip)

**Comment by madxbgt** [comment]
Ok I used build 2328 with MMU 228 but the printer no longer detects that the MMU is connected

**Comment by madxbgt** [comment]
Sorry mate misunderstood your directions, used MK3 2328 with RC4 259 MMU and that has fixed the issue

**Comment by TheZeroBeast** [comment]
Nice 👍 good to hear
