### ISSUE TITLE
How to adjust slic3r for Bondtech-to-nozzle distance

### ISSUE THREAD

**Issue by jettoblack** [TheZeroBeast/MM-control-01#56]
Not a FW bug, but I wasn't sure where else to post this.

I'm trying out a Bondtech BMG-based extruder with indrect filament sensor. I changed the filament sensor to Bondtech gear distance in the MMU2 firmware. But I also need to increase the loading/unloading distance between the Bondtech gears and the nozzle by about 4mm. If I'm right, this is a slic3r setting, not firmware. I thought it might be "Filament parking position" and/or "Extra loading distance" but neither of the tooltips is super helpful.  Any suggestions?

**Comment by TheZeroBeast** [comment]
yes, that 85mm value you would want to modify.

It'll be a tricky change as hardcoded MK3 and MMU loads are going to out of sync.
Mightn't be much grinding hopefully.

**Comment by AbeFM** [comment]
You decrease filament_lookup_table[2][0] (less feed towards gears), increase the "Parking Position" (more feed to nozzle) and you'll get the same loads.

Same for increasing parking position and decreasing  the "Extra Loading Distance", which will basically change where the filament starts from, but in your case ALL you have to do is increase the parking position - then you'll tune the "extra distance" until you get correct purge tower amounts.
