### ISSUE TITLE
Stopping randomly as if MMU2 missed a toolChange command from MK3

### ISSUE THREAD

**Issue by TheZeroBeast** [TheZeroBeast/MM-control-01#6]

**Comment by TheZeroBeast** [comment]
Master-Patch1 is being tested regarding this issue.

**Comment by TheZeroBeast** [comment]
I think all aspects are covered now for ack on all commands to MMU2 apart from P0 as this can be done later if needed. Final testing before versioning and merging to master.

**Comment by AbeFM** [comment]
Looking forward to trying this. My shipment from Prusa is taking a while to go out, so I'm not sure when the new sensor will come. I may try to test the old one to see if it works despite the physical damage.

**Comment by TheZeroBeast** [comment]
Yes, interested to see if your sensor still picks anything up.

This issue is now resolved with Patch1 pegged for merge into master once other issues are resolved.

**Comment by AbeFM** [comment]
Looking forward to trying it. I was hoping to have it today but now it looks like Monday at the soonest. Actually, Tue+ because Monday is a holiday.
