### ISSUE TITLE
Print Complete Timing / Termination Issue

### ISSUE THREAD

**Issue by RJ-Make** [TheZeroBeast/MM-control-01#60]
2nd attempt at dual color printing (ABS) completed (I'm pretty sure it did at least.. :-) ) but OctoPrint though there was more to print?

This is a strange one. I wasn't right in front of the machine when this happened but it looks like the print completed (extruder moved to the 'park' position, and the bed moved forward to present), but OctoPrint had 87% completed. The heated bed and extruder continued to heat; the filament partially extracted. I was forced to kill the print remotely so I could not see what was on the MK3 display.

![p_20181216_080015](https://user-images.githubusercontent.com/8496835/50054372-28134700-010f-11e9-862c-5984aa7961f2.jpg)

![p_20181216_084530_1_p](https://user-images.githubusercontent.com/8496835/50054378-2cd7fb00-010f-11e9-9842-149227c552ee.jpg)

**Comment by RJ-Make** [comment]
Scratch the above, :-)  I don't think it completed. Upon further inspection it appears the MMU gear eat through the green filament causing it not to eject.

**Comment by TheZeroBeast** [comment]
Ah ok, just for the record, is this with that build I sent you zipped? MK3-BN-2328?
