### ISSUE TITLE
Use of Tx and Tc seems to stall/confuse the loading process.

### ISSUE THREAD

**Issue by AnatomicFlack** [TheZeroBeast/MM-control-01#65]
I'm using Tx and Tc during single filament prints and I'm getting an odd behavior when doing so.  

When I use them, Tx before the bed and nozzle are fully preheated, and Tc, after bed and nozzle are up to temp and bed level, has been completed.  The Idler sits in a sort of limbo state and the MMU becomes completely unresponsive after feeding the filament to the sensor waiting for the MK3 to pull it into the extruder for initial load.  The result is that the idler bearing for the loaded filament just sits on top of the hobbed gear so it not moving out of the way and the filament has to force rotate the loading stepper because of the pressure on the gear from the bearing.  

When the print finishes if I leave everything as is when it's time for the unload the extruder unloads to the top of the body properly, but the MMU just sits there with "unloading filament x" on the LCD and never does anything and all buttons are unresponsive.  It requires a restart to get things back up and running again.  

I hope I've explained this correctly.  I'm not sure if this is because there is such a long time delay between heating/leveling and my issuing the second command.  Perhaps I'm hitting some sort of a timeout on loading when there is a gap between Tx and Tc.

**Comment by TheZeroBeast** [comment]
Hey AnatomicFlack,

I'll check this when I can, I tried Tx this morning and had it ask for filament @ MK3 then loaded to bondtech, is this the desired behaviour of this command as per stock?

Tc then loading to nozzle from bondtech?

**Comment by AnatomicFlack** [comment]
That is correct as far as I understand Tx and Tc.  

This issue appears related as I believe they may be using the same commands: https://github.com/TheZeroBeast/MM-control-01/issues/62

**Comment by TheZeroBeast** [comment]
Hey AnatomicFlack,

I have tested and it works now on my latest source, I'm getting people like yourself with issues to do a test before I update my releases page.

Please post back any issues.
see bellow for zip

**Comment by AnatomicFlack** [comment]
I'm unable to flash the MMU with BN260.  The MK3 BM2330 firmware flashed fine, but the MMU2 firmware is acting strangely.  When using slic3r to flash it, it doesn't autodetect the MMU2 when I select any of your other previous builds (or official MMU2 firmwares) and I keep getting the following error on flash attempt:

```
avrdude: Version 6.3-20160220-prusa3d, compiled on Nov 22 2018 at 15:22:47
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:/PROGRA~1/Prusa3D/Slic3rPE/resources\avrdude\avrdude.conf"

         Using Port                    : COM3
         Using Programmer              : wiring
         Overriding Baud Rate          : 115200
avrdude: stk500v2_recv(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer

avrdude done.  Thank you.
```

I am able to flash to BN259 without issue doing everything the exact same way, so I don't believe it's operator error, but I could be wrong.  So I'm not sure what's up.  I even tried flashing in different sequence, MK3, then MMU, reversed, trying with an official Prusa firmware on each, trying with a previous version of yours on each.  BN260 doesn't seem to want to cooperate.  

As a random note of mention: when doing all this while on BN259 I noticed the MMU was showing up twice under the MK3 support menu.  Not sure if it's just a harmless "additional feature" or something else to investigate.  

I miss your firmware... the MMU2 is SOOOOOO slow without it.

**Comment by TheZeroBeast** [comment]
Sorry mate 🤦‍♂️ Forgot to do the line at the top to be able to flash, have a look at the readme please. I’ll send a new copy with it done once I’m awake 👍

**Comment by AbeFM** [comment]
What line? I'll give it a spin if I get clear idea of what versions of
everything to install. :-)

                  Thanks!
                          -Abe.

**Comment by TheZeroBeast** [comment]
[MMU2-2.1.5-BN260.zip](https://github.com/TheZeroBeast/MM-control-01/files/2704562/MMU2-2.1.5-BN260.zip)

**Comment by AbeFM** [comment]
`// public variables:
int8_t filament_type[EXTRUDERS] = { 0, 0, 0, 0, 0};
const int filament_lookup_table[8][3] =
            /*0*/  /*1*/  /*0*/
    /*0*/ {{4600,   400, 2800},
    /*1*/  {2500,   100, 1500}, //Abe was 4000 -> 1500
    /*2*/  { 715,   755,  735}, //Abe longer sensor-gear distance, was 300
    /*3*/  {-610,  -610, -610},
    /*4*/  {6000, 10000, 6500},
    /*5*/  { 600,   300,  550},
    /*6*/  { 350,   200,  385},
    /*7*/  { 400,   200,  455}
};`

Can you stick that in?

**Comment by AbeFM** [comment]
Looks like that should be:
```            /*0*/  /*1*/  /*2*/```
not
```            /*0*/  /*1*/  /*0*/```

**Comment by AbeFM** [comment]
TIL if you flash the MMU first, it hangs the mk3 and you can't flash the mk3 till you downgrade the MMU so it stops messing with the mk3., It's sending something on serial and then maybe not responding,. Resetting the MMU and waiting til it gives up clears it, but you still can;t flash.

Working fine now - on older builds, I can bypass MMU with a rod in the sensor. :-)

**Comment by TheZeroBeast** [comment]
Yep, that’s understandable given the comms changes

**Comment by AnatomicFlack** [comment]
Thanks, flashed perfectly.

It's refreshing when it's not a [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC) issue. 

I'll let you know how it goes after I run it through some prints.

**Comment by AnatomicFlack** [comment]
Problem solved.  Test print with Tx/Tc ran as expected without issue.  I was also able to run the First Layer Calibration without issue.  So it would appear Tx and Tc work properly in this firmware.  Thank you.  

I wanted to tell you sooner... amazing job with this... I only hope that Prusa will wake up and realize you have the proper approach here.  Pairing an indirect filament sensor setup using Prusa's own sensor with your firmware approaches some pretty amazing levels of reliability!

**Comment by TheZeroBeast** [comment]
Good to hear, I'll push it out to all after a bit further testing.

Thank you, appreciate your comments 😊
