### ISSUE TITLE
Poor Drum Control During load/unload (Video)

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#66]
2324/257

Watch this video. It's 3.5 minutes, watch as much as you need.

When I do a middle button "load", the drum rotates into place, feeds the filament, unfeeds it. then the drum "relaxes".

On channel 3 (and to a lesser degree on channel 4 - but 1, 2, and 5 are SOLID as described above) the drum flips a bit when the drive changes direction. 

I suspect it means there's either not enough current driving it into place, or too little holding it. My scews are one tun past flush so I hope that it's not out of torque!

Video: Last item in album, 3:20, click to view. And turn down speakers, I was loud! https://photos.app.goo.gl/KLS7XDsEsLe2dryc7

**Comment by TheZeroBeast** [comment]
I'll take a look when I can, just as a note my bolts are always set at 2.5turns past flush.

**Comment by AbeFM** [comment]
That's why I brought it up - it shouldn't be an issue on my light tension.

I typically run flush and it works fine, I'm not convinced more pressure helps.... Or at least every time I had issues I found other ways to maintain the speed. or that tightening the screws didn't fix the problem.

As I'm having weak initial extrusions *specifically* on that/those channels, I'd like to figure this out.

**Comment by TheZeroBeast** [comment]
Looks like it's loosing steps in your video but I'll have a look closer when I can, might be able to up current for the short time it is engaged or something to hold.

**Comment by AbeFM** [comment]
Given the timing, there's a chance it's relaxing just during the switch from forwards to backwards?

My real concern is that something like that is effecting general loading/unloading enough to trigger one of these rare failures. My first layers are always weak on that channel (since I've gone to the optically triggered firmwares)

**Comment by TheZeroBeast** [comment]
I have had a good look and don’t personally get any unwanted stepper movements as per your videos. You might need to troubleshoot further on your end.

All I can think is that it’s not holding enough on those engagements.

Maybe increasing stepper holding current will do it for you, might be the stepper will be too hot then.

**Comment by TheZeroBeast** [comment]
Further improvements with 2.1.6, still no sign of this issue personally. If you're able to improve the code please submit a pull-request.
