### ISSUE TITLE
easy way to switch to non-mmu prints?

### ISSUE THREAD

**Issue by diomark** [TheZeroBeast/MM-control-01#67]
With the stock firmware, if I have something in the path of the mmu's filament sensor, the mmu blinks all red and I can use the mk3 without it (it doesn't detect it and works like the old mk3) - this is actually very helpful as sometimes we need to print with materials that the MMu doesn't handle well (like, tpu or ninjaflex)

I can't find an easy way to turn off the MMU with this firmeware. (only thing that works is manually unplugging it's connectors..)

Would love to see an option to disable the MMU for these types of situations.

**Comment by TheZeroBeast** [comment]
You can load TPU fine with my FW as long as you select FLEX type in Slic3r. Especially for single colour prints. The unload sequence for FLEX still needs work.

Please note stock FW is similar on boot with filament as mine now so it will always connect.

**Comment by AbeFM** [comment]
The more I think about it, the only REAL solution is a switch on the power (signal?) lines between mk3 and MMU.

Its's a case where $1 will replace a lot of progamming.

**Comment by diomark** [comment]
In my case, I've got a 3 spools that stayed in the oven for too long. Feeds direct just fine, but no way is it working if it has to be fed through a ptfe tube..   AbeFM - your power switch idea is a pretty good idea.. just need to isolate which wire which shouldn't be too hard..

**Comment by AbeFM** [comment]
Which two. The power cable is 2 each. That's not exactly a problem, but there you go. Respin the board and put both the reset switch and add a power switch to be externally accessible. :-)

Same for the internal lights - the only other feedback you get on reset is 10 seconds later something moves. I've been debating making a new top - especially as I've seen cabling issues I think the whole cover for the PCB in the MMU could be redone with a bunch of changes.

The concern is that leaving the unpowered MMU's serial lines hooked up will pull down something needed in the mk3. It shouldn't be hard to unplug it.

**Comment by TheZeroBeast** [comment]
The only line needed to switch is the 5v line, the remainder can remain on.

I’m going to try add this feature as bellow.

Disable MMU2
Move selector to service position.
Reset MK3

Re-enable MMU2
Move selector off service position.
Resent MK3

**Comment by TheZeroBeast** [comment]
Just tested and this is working great, it'll be there in the 2.1.5 full release.
