### ISSUE TITLE
On failed Load, retract a bit!

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#68]
If I load filament, and the MMU pulls it into the selector but then gives up before seeing the ball rise, the selector attempts to move somewhere (I think to rehome, every other time).

The issue is that the filament it IN the selector, gets bent, causes issues.

It would be better if, after giving up on a load, you retract the MMU at least ~1 cm (distance from ball to selector input).
If you've got no filament, it doesn't matter. If you're just barely on the gears, it might push you out, but I think it'll do more good than harm.

**Comment by TheZeroBeast** [comment]
Hey AbeFM,

I have a slow unload to park on right button when load failed.
Alternatively if it’s possibly a bit in selector the right button moves filament back 15mm each press to cover your situation.

Coming on this full release, just waiting on new fsensor to finish testing.

**Comment by AbeFM** [comment]
Did your sensor also break? I was surprised how readily Prusa offered me a
replacement, maybe I'm not the only one. Maybe I need to print a stain
relief for it.

Why wouldn't you pull the filament back 1 cm or so after a failed load? You
can't see inside, there's no manual intervention needed. Just retract?

                  Thanks!
                          -Abe.
