### ISSUE TITLE
Where is the source code for the MK3 firmware

### ISSUE THREAD

**Issue by YoungR0se** [TheZeroBeast/MM-control-01#72]
Hi,
I'm looking for the source code for the MK3: V#: 5.0.4 RC B#: 2327 firmware that goes with the MMU: V#: 2.1.5 RC B#: 259 firmware.  The HEX file is no good for me, because I need to edit the printer to allow for a taller Z-axis than normal.
Can anyone tell me where to find this code?
Fairfarren

**Comment by TheZeroBeast** [comment]
https://github.com/TheZeroBeast/Prusa-Firmware

**Comment by YoungR0se** [comment]
Ok thanks, only when I verify the build, Arduino gives back a whole A4 page of errors.  And yes, I did follow the README about environment preparation.  Any suggestions?

**Comment by YoungR0se** [comment]
I am using the provided HEX file from https://github.com/TheZeroBeast/MM-control-01/releases form the time being, but I need to be able to edit the firmware because my printer's Z axis is 350mm not 210mm, which is only as high as the HEX is programmed to go...

**Comment by TheZeroBeast** [comment]
I’ll double check it pushed properly.

You got the einsy board installed, selected and the MK3 config is copied into the main folder as configuration_prusa.h?

**Comment by YoungR0se** [comment]
Yes, I have copied the EINSY board file from the Variants folder and renamed it Configuration_prusa

**Comment by TheZeroBeast** [comment]
Are you running latest arduino ide?
What errors as PRUSA code has a whole bunch of warnings but it should still say it compiled at the bottom.

**Comment by YoungR0se** [comment]
The program is Arduino 1.6.9.  Errors include 'mmu_state' was declared 'extern' and later 'static' [-fpermissive], uart2.h:24: error: initializing argument 1 of 'void uart2_txPayload(unsigned char*)' [-fpermissive] extern void uart2_txPayload(unsigned char payload[3]);, mmu.cpp:312: error: invalid conversion from 'char*' to 'unsigned char*' [-fpermissive] uart2_txPayload(tempFx);

**Comment by YoungR0se** [comment]
If compiled in Arduino 1.8.5, such errors as the following occur: ultralcd.cpp:6540: error: '_stepdone' was not declared in this scope

    _stepdone = true;

    ^

ultralcd.cpp:6557: error: '_stepdone' was not declared in this scope

   (_travel_done <= _travel) ? _travel_done++ : _stepdone = true;

                                                ^

ultralcd.cpp:6559: error: '_stepdone' was not declared in this scope

  } while (!_stepdone);

            ^

ultralcd.cpp:6570: error: '_axis' was not declared in this scope

   if (_axis == X_AXIS) _error_1 = "X";

       ^

ultralcd.cpp:6571: error: '_axis' was not declared in this scope

   if (_axis == Y_AXIS) _error_1 = "Y";

       ^

ultralcd.cpp:6572: error: '_axis' was not declared in this scope

   if (_axis == Z_AXIS) _error_1 = "Z";

       ^

exit status 1
expected initializer before 'bool'

**Comment by TheZeroBeast** [comment]
How did you download the source code? Clone to zip? The errors shown above aren’t in my code.

**Comment by YoungR0se** [comment]
I download a zip folder from the code page

**Comment by TheZeroBeast** [comment]
That page was a snippet in time at the very start of development and isn’t updated. You would need to download to zip from main repository page (green button on right)

https://github.com/TheZeroBeast/Prusa-Firmware

**Comment by YoungR0se** [comment]
Ok, I have done as recommended.  Changed 2 numbers in the code and flashed it to the printer.  It works that much, but the printer does not recognise that there is a MMU unit connected.  The menu shows loading options for a single head setup.

**Comment by YoungR0se** [comment]
Thank you

**Comment by AbeFM** [comment]
Did to also flash matching MMU firmware?

Is there some way to pair them up? It always seems hard to find a matched
set. It almost seems like it would be better under a single revision
control.

I'm probably wrong about that, but it is hard to tell what goes together.
Maybe use the date for revising number?

                  Thanks!
                          -Abe.
