### ISSUE TITLE
Selector doesn't move after Update

### ISSUE THREAD

**Issue by KappaMi** [TheZeroBeast/MM-control-01#73]
I have the problem that after the latest update the selector can no longer move. With the previous firmware it works. I have to manually put the selector to the left and press the middle button.

**Comment by TheZeroBeast** [comment]
Hey KappaMi,
2.1.5 is being released soon which solves this issue.
Please note that selector now never homes at boot due to power panic support.

**Comment by KappaMi** [comment]
Thank you for your reply. This "Issue" is with the latest FW youve made.

**Comment by TheZeroBeast** [comment]
Hey Mate, can you please review this issue in relation to 2.1.5 release yesterday?

**Comment by KappaMi** [comment]
Yes I will do it in 3 hours Mate, thx for the good work :)

**Comment by KappaMi** [comment]
The MMU only moves if i press a button on it. If I dont do it, it doesnt start

**Comment by TheZeroBeast** [comment]
This is how it is meant to be, it shouldn’t fully home until you try do something.

The print starts fine I take it?

**Comment by TheZeroBeast** [comment]
If this is still an issue please reopen.

Please try stock FW to compare the start function, I’m sure you’ll be convinced it is the same desired motions.

**Comment by KappaMi** [comment]
Sorry, I forgot to close it. I tried the Stock FW and immediately flashed again your :D very good work!! :) However, I noticed that the MMU sometimes needs a reset (middle button) during printing to continue working. Once it was also so that nothing worked any more and I had to abort the print. The MMU hasn't stirred itself any more
