### ISSUE TITLE
After idle timeout, selector makes crackling noise while 1st LED blinks red

### ISSUE THREAD

**Issue by jettoblack** [TheZeroBeast/MM-control-01#74]
I'm mostly curious to see if anyone else has noticed this on FW 260 / 2330.

Before the idle timeout occurs, the selector motor makes a kind of "waterfall" noise which is annoying but bearable.

After the idle timeout occurs, the selector motor initially becomes quiet, but after a few minutes starts to emit a steadily increasing crackling noise, and the leftmost LED flashes red in sync with the noise. As time goes on, the noise and blinking will decrease, then increase again, until the selector motor is powered up and goes back to the normal waterfall noise.

I made a video: https://youtu.be/PBR0PyhX09s

Any ideas?

**Comment by TheZeroBeast** [comment]
Thanks Jettoblack, I'll have a look into this.

**Comment by Panayiotis-git** [comment]
I've noticed this also.
Then, if you gently push/twist the power and uart2 connectors on the MMU2, the amplitude of the noise changes.

**Comment by TheZeroBeast** [comment]
2.1.5 release will cover this.
Think I’ve fixed this mate. Disable all steppers was running every loop when timed out. Now it does it once.

This was causing enable pins to come on for a few micro seconds a cycle.

This is tied with LEDs as Stepper Dir, Ena and LEDs are on the shift register.
