### ISSUE TITLE
No filament loading after first homing

### ISSUE THREAD

**Issue by Panayiotis-git** [TheZeroBeast/MM-control-01#77]
If the MMU is not homed, the press of any button first triggers the homing procedure and then does the appropriate function.

In the case of the middle button press, after the initialization, the filament loading is skipped.

Present in git commit https://github.com/TheZeroBeast/Prusa-Firmware/commit/cd6998ffc69ef5ed86633cc5c3d25eacd922095e

Fix:
In mmctl.cpp (ln 32) instead of
`    else if (!digitalRead(A1)) {`
it should be
`    if (!digitalRead(A1)) {`

Keep the nice work!

**Comment by TheZeroBeast** [comment]
I had noticed this and agree it makes more sense to do the action once homed like left and right. Pegged for next release.

**Comment by AbeFM** [comment]
There's certainly a chance this is part of my button issue.

                  Thanks!
                          -Abe.

**Comment by TheZeroBeast** [comment]
This has been added to next release 2.1.6 which is a few weeks off.
