### ISSUE TITLE
Load Filament x command from printer do not light the red LED

### ISSUE THREAD

**Issue by Panayiotis-git** [TheZeroBeast/MM-control-01#78]
When user selects to load a filament from the MMU buttons, the unit lights the appropriate red LED, does the loading and then lights the green LED.

When the user selects to load a filament from the printer's menu, the unit moves to the selected filament and starts the loading without lighting the appropriate red LED.

Present in git commit https://github.com/TheZeroBeast/Prusa-Firmware/commit/cd6998ffc69ef5ed86633cc5c3d25eacd922095e

Fix:
In the main.cpp (ln 157) inside the loop() method, the code lights the red LED.

```
shr16_clr_led();
shr16_set_led(2 << 2 * (4 - active_extruder));
```

These lines should be removed from there and moved to the mmctl.cpp (ln 33) inside the method
```
bool feed_filament(void)
{
    bool _loaded = false;
    if (!isHomed && !isFilamentLoaded) home(true);
    if (!digitalRead(A1)) {
        int _c = 0;
        shr16_clr_led();
        shr16_set_led(2 << 2 * (4 - active_extruder));
        engage_filament_pulley(true);
```

**Comment by TheZeroBeast** [comment]
Nice pickup, thank you for your clear description, I'll get this done for 2.1.6

**Comment by TheZeroBeast** [comment]
This has been added to next release 2.1.6 which is a few weeks off.
