### ISSUE TITLE
Firmware tweaking for [redacted] extruder install

### ISSUE THREAD

**Issue by AbeFM** [TheZeroBeast/MM-control-01#82]
I'm trying to use a belt-reduced-drive extruder with an indirect filament sensor), now, and now the buttons don't work at all. Kinda up a creek on this one, Prusa, you and [anonymous creator] are all at someone else's mercy. 
I have a few issues:
**1) Filament doesn't unload completely from extruder before MMU pulls on it,** stripping filament and failing.
I'm wondering if the steps to unload filament is hard coded?

Some loads and unloads:
```start
echo: 5.0.4-TZB-2330
echo: Last Updated: Dec 29 2018 11:21:36 | Author: (none, default config)
Compiled: Dec 29 2018
echo: Free Memory: 2010  PlannerBufferBytes: 1392
echo:Stored settings retrieved
adc_init
CrashDetect ENABLED!
PAT9125_RES_X=0
PAT9125_RES_Y=240
PAT9125_init:1
PAT9125_RES_X=0
PAT9125_RES_Y=240
PAT9125_init:1
FSensor ENABLED
echo:SD card ok
echo:busy: processing
echo:busy: processing
fsensor_autoload_check_start - autoload ENABLED

MMU => MK3 '215'
MMU => MK3 '260'
MMU version valid
MMU - ENABLED
PAT9125_RES_X=0
PAT9125_RES_Y=240
PAT9125_init:1
echo:enqueing "M701 E0"
gcode_M701 begin
MK3 => MMU 'L0'
echo:busy: processing
echo:busy: processing
echo:busy: processing
MMU => MK3 'ok'
MK3 => MMU 'U0'
MMU => MK3 'ok'
E-AXIS Disabled.
MK3 => MMU 'T0 @toolChange:1'
echo:busy: processing
echo:busy: processing
MMU => MK3 'waiting for filament @ MK3 Sensor'
fsensor_autoload_check_stop - autoload DISABLED

fsensor_autoload_check_start - autoload ENABLED

echo:busy: processing
fsensor_autoload_check_stop - autoload DISABLED

MK3 => MMU 'Filament seen at extruder'
MMU => MK3 'ok'
E-AXIS Enabled.
MK3 => MMU 'C0'
echo:busy: processing
MMU => MK3 'ok'
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: paused for user
echo:enqueing "M702 C"
echo:busy: processing
echo:busy: processing
MK3 => MMU 'U0'
fsensor_autoload_check_start - autoload ENABLED

echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
MMU => MK3 'ok'
echo:enqueing "M701 E0"
gcode_M701 begin
MK3 => MMU 'L0'
echo:busy: processing
MMU => MK3 'ok'
MK3 => MMU 'U0'
MMU => MK3 'ok'
E-AXIS Disabled.
MK3 => MMU 'T0 @toolChange:1'
echo:busy: processing
echo:busy: processing
MMU => MK3 'waiting for filament @ MK3 Sensor'
fsensor_autoload_check_stop - autoload DISABLED

fsensor_autoload_check_start - autoload ENABLED

echo:busy: processing
fsensor_autoload_check_stop - autoload DISABLED

MK3 => MMU 'Filament seen at extruder'
MMU => MK3 'ok'
E-AXIS Enabled.
MK3 => MMU 'C0'
echo:busy: processing
MMU => MK3 'ok'
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: paused for user
echo:busy: paused for user
E-AXIS Disabled.
MK3 => MMU 'E0'
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
echo:busy: processing
MMU => MK3 'ok'
E-AXIS Enabled.
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
MK3 => MMU 'R0'
echo:busy: processing
echo:busy: processing
MMU => MK3 'ok'
echo:enqueing "M701 E0"
gcode_M701 begin
MK3 => MMU 'L0'
echo:busy: processing
MMU => MK3 'ok'
```
As the extruder is being disabled right when the filament is getting stuck in the extruder, I fear that may be the cause.

Works now
_2) Buttons on front panel don't work
Yeah. Pressing them does nothing. I have no idea why, the only MMU code I changed was the speed array thing. Changes on mk3, but that shouldn't matter??_
feature request, ignore:
_3) I'd still like a way to set the sensor-gear distance, flash and guess and flash is tough, especially since the filament doesn't pause at the "gear location", so it's hard to tell where the handoff happens._

**Comment by AbeFM** [comment]
Works now, had to clear and recal xyz
_4) When loading filament, nothing comes out of the nozzle. It appears to under-load.
This is weird since the tube got shorter and I believe I fixed steps/mm. I think #1 and #5 are related._

5) Z dimension shows up as "?", live Z appears to work, though it's with "?" being shown as the dimension.
5b) ALL dimensions show up as "?", even after homing.

**Comment by AbeFM** [comment]
M503 gives me: 


```

MMU => MK3 '215'
MMU => MK3 '260'
MMU version valid
MMU - ENABLED
PAT9125_RES_X=0
PAT9125_RES_Y=240
PAT9125_init:1
echo:Steps per unit:
echo:  M92 X? Y? Z? E?
echo:Maximum feedrates - normal (mm/s):
echo:  M203 X? Y? Z? E?
echo:Maximum feedrates - stealth (mm/s):
echo:  M203 X? Y? Z? E?
echo:Maximum acceleration - normal (mm/s2):
echo:  M201 X1000 Y1000 Z200 E5000
echo:Maximum acceleration - stealth (mm/s2):
echo:  M201 X960 Y960 Z200 E5000
echo:Acceleration: S=acceleration, T=retract acceleration
echo:  M204 S? T?
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S? T? B? X? Y? Z? E?
echo:Home offset (mm):
echo:  M206 X? Y? Z?
echo:PID settings:
echo:   M301 P? I? D?
echo:PID heatbed settings:
echo:   M304 P? I? D?
echo:Retract: S=Length (mm) F:Speed (mm/m) Z: ZLift (mm)
echo:   M207 S? F? Z?
echo:Recover: S=Extra length (mm) F:Speed (mm/m)
echo:   M208 S? F?
echo:Auto-Retract: S=0 to disable, 1 to interpret extrude-only moves as retracts or recoveries
echo:   M209 S0
echo:Filament settings: Disabled
ok
```

Looks like lots of stuff is weird.

**Comment by AbeFM** [comment]
I get the same behavior if I compile untweaked 2330 code.

**Comment by AbeFM** [comment]
M92 doesn't report, nor does it store changes if I send something like M92 X100
M203 doesn't work either. Could it be a serial coms issue, Rob?

**Comment by AbeFM** [comment]
After reseting XYZ cal, and recalibrating it all, it behaves the same.

I adjust liveZ and the value stays but does not display on screen.


I adjusted PID fom the menu on the printer, but afterwards it still won't report values:
```T:212.40 @:0
T:211.35 @:0
T:210.00 @:0
 bias: 65 d: 65 min: 207.63 max: 212.66
 Ku: 32.96 Tu: 21.90
 Classic PID 
 Kp: 19.77
 Ki: 1.81
 Kd: 54.14
PID Autotune finished! Put the last Kp, Ki and Kd constants from above into Configuration.h
echo:enqueing "M301 P019.77 I001.80 D054.13"
echo:enqueing "M500"
ok p:19.77 i:1.80 d:54.13 c:1.00
echo:Settings Stored
echo:Steps per unit:
echo:  M92 X? Y? Z? E?
echo:Maximum feedrates - normal (mm/s):
echo:  M203 X? Y? Z? E?
echo:Maximum feedrates - stealth (mm/s):
echo:  M203 X? Y? Z? E?
echo:Maximum acceleration - normal (mm/s2):
echo:  M201 X2500 Y1000 Z200 E5000
echo:Maximum acceleration - stealth (mm/s2):
echo:  M201 X960 Y960 Z200 E5000
echo:Acceleration: S=acceleration, T=retract acceleration
echo:  M204 S? T?
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S? T? B? X? Y? Z? E?
echo:Home offset (mm):
echo:  M206 X? Y? Z?
echo:PID settings:
echo:   M301 P? I? D?
echo:PID heatbed settings:
echo:   M304 P? I? D?
echo:Retract: S=Length (mm) F:Speed (mm/m) Z: ZLift (mm)
echo:   M207 S? F? Z?
echo:Recover: S=Extra length (mm) F:Speed (mm/m)
echo:   M208 S? F?
echo:Auto-Retract: S=0 to disable, 1 to interpret extrude-only moves as retracts or recoveries
echo:   M209 S0
echo:Filament settings: Disabled
ok```


The extruder steps are right, it's the screen that isn't displaying right.

**Comment by AbeFM** [comment]
Didn't I have this issue before, with variables not showing up?

There's some tweak made to the Prusa FW, I think, that allowed the values to display, can you remind me?

It looks like there are missing commands. I was watching the serial output:
```
 E/D=Auto
Unknown G code: G21
```
Coupled with: **G21: Set Units to Millimeters**
That explains a lot. I can't find G21 anywhere. Pehaps it could be done explicitly instead of with gcode?

**Comment by TheZeroBeast** [comment]
Hey,
G21 has always done that in PRUSA FW for me anyway, it may just be hard coded to mm.

The not desolating thing is fprint not enabled for the arduino compiler. Check readme on where to add that parameter.

To change load/unload distances for a print it’s Slic3r but for all the inbuilt functions you’d have to track down where and update accordingly.

The stepper disable is what PRUSA do at the same time in unload, motor is free to turn.
I do see malformed ends get snagged a bit and haven’t been thinking of a solution, stay tuned.

The button thing, are you holding buttons long enough to trigger? They aren’t on interrupts yet.

**Comment by AbeFM** [comment]
A bunch of that stuff started working.

I have made the changes to the environment, everything's been working fine for a month there.

G21 doesn't work for you either? Whatever hard coding there was is somehow missing now.

The extruder should unload filament past itself, just to be sure, no?

Even with MMU unplugged I get this no such thing as mm's issue.

**Comment by TheZeroBeast** [comment]
Check G21 in stock FW, see if you can see it doing anything.

Yes, that’s the -85 in Slic3r, the park distance can be increased.

I’m going to try sync the unload so they don’t fight when it still has a small blob in bondtech.

**Comment by AbeFM** [comment]
The not feeding/loading/unloading was the steps/mm being wrong. Somehow after recalibrating XYZ, that now works. I shouldn't have to tweak the "-85"

**Comment by AbeFM** [comment]
Reinstalling the IDE fixed this.

**Comment by Panayiotis-git** [comment]
For the "buttons not working" issue, perhaps you have issued a Tn command (from an abandoned print?). From this point the MMU unit will not respond to buttons as usual until you issue an unload command.
