### ISSUE TITLE
Feature Request 7x7 Mesh Bed Levelling

### ISSUE THREAD

**Issue by gizzburn** [TheZeroBeast/MM-control-01#83]
Hi awesome job on the firmware, is there any chance you could incorporate the new mesh 9 point bed leveling code in to your firmware in the next update, I tried it on the stock firmware on the Prusa MMU2 Fb page and it was loads better, this would be a great addition to your firmware.

thanks

**Comment by danielegger1** [comment]
Thumbs up on that.
As far as I understand the new change in the fw it will be 3x3 or 7x7 possible just the additional N7 value at the G80 code.

**Comment by TheZeroBeast** [comment]
Yeah, for sure, could you point me to the GitHub in question?

**Comment by gizzburn** [comment]
I think this is the link your asking for...

https://github.com/prusa3d/Prusa-Firmware/issues/1239?fbclid=IwAR0tLZ61_lKBObPWM6iRfjwvAsUM8DGCQPkq93tuAIz7x8BEYztbj8rXsek#issuecomment-450579217

**Comment by TheZeroBeast** [comment]
I have merged and going to do a couple tests. This will be in 2.1.6

**Comment by gizzburn** [comment]
Great cant wait for the file..

**Comment by TheZeroBeast** [comment]
This has been adding in 2.1.6, feel free to give it a go.

https://github.com/TheZeroBeast/MM-control-01/releases
