### ISSUE TITLE
Check hotend temp and perform unload before attempting unload via the MMU.

### ISSUE THREAD

**Issue by Mjankor** [TheZeroBeast/MM-control-01#84]
When doing single material prints, I'm often seeing the MMU trying to unload filament that's locked in the extruder. It seems to be due to the handling of the Tc code.
I'm wondering if the unload_filament_withSensor function should have a check on hotend temp, and attempt an unload from the extruder first.

**Comment by TheZeroBeast** [comment]
Please submit an issue with Prusa MK3 Firmware to have this issue looked into.

On a side note I find it easier to Slic3r single colour prints with MMU2 Slic3r profile and only one colour, the purge block then doesn't get added.

If on another note you want to just disable MMU2 and do some prints you can leave the selector in service position and restart MK3.
