### ISSUE TITLE
Implementing fast PWM to reduce cooling fan noise

### ISSUE THREAD

**Issue by ssvenn** [TheZeroBeast/MM-control-01#87]
Could we merge this? https://github.com/prusa3d/Prusa-Firmware/pull/1193

It's a small modification but it reduces fan noise considerably at low duty cycles, especially when the extruder has been upgraded to the angled design. It breaks RPM monitoring and supposedly makes the mostfet for the fan run hotter but the annoying whine from the fan is driving a lot of use completely crazy :)

I think Prusa is waiting for more in-house testing before they merge it in their own fw, or maybe looking for other solutions. I wish I could find a compatible four-wire fan with native PWM support, then the whole issue would be moot.

**Comment by TheZeroBeast** [comment]
Sorry, I'd prefer to wait for prusa testing and limit the additional modifications so stock.
