### ISSUE TITLE
Doubt on bowden tube calibration 

### ISSUE THREAD

**Issue by adlamy** [TheZeroBeast/MM-control-01#88]
When doing the bowden tube calibration, filament aligned with end of bowden tube and press left button to save settings, I noticed each time I did the procedure again, that the filament doesn't reach the same position previously saved, it stand back from the bowden tube end for about 4/5mm.
Is it wanted or is it a bug ?

Otherwise since MMU 2.1.5 & MK3 5.0.4-TZB release your firmware is realy fantastic. Thanks a lot for your great job.

André.

**Comment by TheZeroBeast** [comment]
this is intended although done so neater in 2.1.6 so each time it goes to the same testing length.

thank you
