### ISSUE TITLE
Testing build 2390 MK3 Firmware

### ISSUE THREAD

**Issue by madxbgt** [TheZeroBeast/MM-control-01#89]
Just testing build 2390 and after flashing Z axis has ? in display, wondering if this is an issue with the FW or because still being cleaned up?
![20190112_090151](https://user-images.githubusercontent.com/45223966/51064015-51a98a80-1649-11e9-9e42-ddf3c5567d44.jpg)

**Comment by TheZeroBeast** [comment]
The ? is due to not setting up your compiler to support fprint, 2.1.6/2390 is still in development, if you're trying to compile latest release you can download the zip source from the releases page.

**Comment by madxbgt** [comment]
Ah ok, thankyou, fixed it up just testing out the 7x7 leveling

**Comment by TheZeroBeast** [comment]
No worries, it is very cool. I'm just working on the last couple features before I release with 7x7. sing out if you want a zip with the 7x7 alpha built to alpha test.

**Comment by madxbgt** [comment]
Thanks mate, if you have time, would really appreciate it
