### ISSUE TITLE
When recovering from a failed load the next adjacent filament extrudes in line with C0 command

### ISSUE THREAD

**Issue by TheZeroBeast** [TheZeroBeast/MM-control-01#9]

**Comment by AbeFM** [comment]
My feeling here is when the MMU comes up, it should be able to ask the Mk3 what state it SHOULD be in (what filament, fed or unfed) and then see if it cannot GET there before returning.

After watching them work, I really think it needs to be a group effort.

**Comment by TheZeroBeast** [comment]
Yes, for sure 👍

**Comment by TheZeroBeast** [comment]
Fixed by the following commits.
https://github.com/TheZeroBeast/MM-control-01/commit/8905f7e452cab6d52e4efc9ad9cf70f927f112db
https://github.com/TheZeroBeast/Prusa-Firmware/commit/c2c2fd3d2fa57b4232b1e99e005d3e877a7aca7e
