### ISSUE TITLE
Troubleshooting state difficult to use

### ISSUE THREAD

**Issue by aarchiba** [TheZeroBeast/MM-control-01#94]
I have been having filament switch failures (not the problem), and in the "troubleshooting" state I am getting mysterious misbehaviour:
* right button does nothing
* current filament LED flashes green
* middle button switches LED to steady green for a few seconds then goes back to blinking; no motor activity
* no message on LCD

I think this is occurring because the MK3 filament sensor is sending spurious readings, but there's no indication anywhere of what reading it is giving or whether this is the problem. Would it be possible to make the LCD display the current state of the filament sensor so my debugging can have something to work with? For that matter, troubleshooting instructions on the LCD would be great, describing the current error state (e.g. "Trying to unload but filament detected in extruder but not in FINDA"). 

Whatever the state, it would be nice if the right button worked whenever the FINDA was triggered to pull the filament back out of the selector but not past the ability to feed - currently I have to do this by yanking on the filament and there's some guesswork involved.

**Comment by TheZeroBeast** [comment]
Please provide a video of the state with the gcode you were printing at the time.

At present when in error state left button attempts to push active_mmu_filament and right attempts to retract to park if FINDA is tripped or back 20mm if not.

You would never get into the example provided unless FINDA isn't setup correctly.

**Comment by TheZeroBeast** [comment]
Closing due to lack of communication.
